// Auto-generated by scripts/generate-data.mjs. Do not hand-edit generated
// question/answer text here directly for extraction fixes -- edit the
// QUESTION_FIXES/OPTION_FIXES maps in that script and re-run it instead.
export default {
  questions: {
    question_1: {
      question: 'In Deutschland dürfen Menschen offen etwas gegen die Regierung sagen, weil ...',
      answer_a: 'hier Religionsfreiheit gilt.',
      answer_b: 'die Menschen Steuern zahlen.',
      answer_c: 'die Menschen das Wahlrecht haben.',
      answer_d: 'hier Meinungsfreiheit gilt.'
    },
    question_2: {
      question:
        'In Deutschland können Eltern bis zum 14. Lebensjahr ihres Kindes entscheiden, ob es in der Schule am ...',
      answer_a: 'Geschichtsunterricht teilnimmt.',
      answer_b: 'Religionsunterricht teilnimmt.',
      answer_c: 'Politikunterricht teilnimmt.',
      answer_d: 'Sprachunterricht teilnimmt.'
    },
    question_3: {
      question: 'Deutschland ist ein Rechtsstaat. Was ist damit gemeint?',
      answer_a: 'Alle Einwohnerinnen/Einwohner und der Staat müssen sich an die Gesetze halten.',
      answer_b: 'Der Staat muss sich nicht an die Gesetze halten.',
      answer_c: 'Nur Deutsche müssen die Gesetze befolgen.',
      answer_d: 'Die Gerichte machen die Gesetze.'
    },
    question_4: {
      question: 'Welches Recht gehört zu den Grundrechten in Deutschland?',
      answer_a: 'Waffenbesitz',
      answer_b: 'Faustrecht',
      answer_c: 'Meinungsfreiheit',
      answer_d: 'Selbstjustiz'
    },
    question_5: {
      question: 'Wahlen in Deutschland sind frei. Was bedeutet das?',
      answer_a: 'Man darf Geld annehmen, wenn man dafür eine bestimmte Kandidatin/einen bestimmten Kandidaten wählt.',
      answer_b: 'Nur Personen, die noch nie im Gefängnis waren, dürfen wählen.',
      answer_c:
        'Die Wählerin/der Wähler darf bei der Wahl weder beeinflusst noch zu einer bestimmten Stimmabgabe gezwungen werden und keine Nachteile durch die Wahl haben.',
      answer_d: 'Alle wahlberechtigten Personen müssen wählen.'
    },
    question_6: {
      question: 'Wie heißt die deutsche Verfassung?',
      answer_a: 'Volksgesetz',
      answer_b: 'Bundesgesetz',
      answer_c: 'Deutsches Gesetz',
      answer_d: 'Grundgesetz'
    },
    question_7: {
      question:
        'Welches Recht gehört zu den Grundrechten, die nach der deutschen Verfassung garantiert werden? Das Recht auf ...',
      answer_a: 'Glaubens- und Gewissensfreiheit',
      answer_b: 'Unterhaltung',
      answer_c: 'Arbeit',
      answer_d: 'Wohnung'
    },
    question_8: {
      question: 'Was steht nicht im Grundgesetz von Deutschland?',
      answer_a: 'Die Würde des Menschen ist unantastbar.',
      answer_b: 'Alle sollen gleich viel Geld haben.',
      answer_c: 'Jeder Mensch darf seine Meinung sagen.',
      answer_d: 'Alle sind vor dem Gesetz gleich.'
    },
    question_9: {
      question: 'Welches Grundrecht gilt in Deutschland nur für Ausländerinnen/Ausländer? Das Grundrecht auf ...',
      answer_a: 'Schutz der Familie',
      answer_b: 'Menschenwürde',
      answer_c: 'Asyl',
      answer_d: 'Meinungsfreiheit'
    },
    question_10: {
      question: 'Was ist mit dem deutschen Grundgesetz vereinbar?',
      answer_a: 'die Prügelstrafe',
      answer_b: 'die Folter',
      answer_c: 'die Todesstrafe',
      answer_d: 'die Geldstrafe'
    },
    question_11: {
      question: 'Wie wird die Verfassung der Bundesrepublik Deutschland genannt?',
      answer_a: 'Grundgesetz',
      answer_b: 'Bundesverfassung',
      answer_c: 'Gesetzbuch',
      answer_d: 'Verfassungsvertrag'
    },
    question_12: {
      question: 'Eine Partei im Deutschen Bundestag will die Pressefreiheit abschaffen. Ist das möglich?',
      answer_a: 'Ja, wenn mehr als die Hälfte der Abgeordneten im Bundestag dafür sind.',
      answer_b: 'Ja, aber dazu müssen zwei Drittel der Abgeordneten im Bundestag dafür sein.',
      answer_c: 'Nein, denn die Pressefreiheit ist ein Grundrecht. Sie kann nicht abgeschafft werden.',
      answer_d: 'Nein, denn nur der Bundesrat kann die Pressefreiheit abschaffen.'
    },
    question_13: {
      question: 'Im Parlament steht der Begriff "Opposition" für ...',
      answer_a: 'die regierenden Parteien.',
      answer_b: 'die Fraktion mit den meisten Abgeordneten.',
      answer_c: 'alle Parteien, die bei der letzten Wahl die 5%-Hürde erreichen konnten.',
      answer_d: 'alle Abgeordneten, die nicht zu der Regierungspartei/den Regierungsparteien gehören.'
    },
    question_14: {
      question: 'Meinungsfreiheit in Deutschland heißt, dass ich ...',
      answer_a: 'Passanten auf der Straße beschimpfen darf.',
      answer_b: 'meine Meinung im Internet äußern kann.',
      answer_c: 'Nazi-, Hamas- oder Islamischer Staat-Symbole öffentlich tragen darf.',
      answer_d: 'meine Meinung nur dann äußern darf, solange ich der Regierung nicht widerspreche.'
    },
    question_15: {
      question: 'Was verbietet das deutsche Grundgesetz?',
      answer_a: 'Militärdienst',
      answer_b: 'Zwangsarbeit',
      answer_c: 'freie Berufswahl',
      answer_d: 'Arbeit im Ausland'
    },
    question_16: {
      question: 'Wann ist die Meinungsfreiheit in Deutschland eingeschränkt?',
      answer_a: 'bei der öffentlichen Verbreitung falscher Behauptungen über einzelne Personen',
      answer_b: 'bei Meinungsäußerungen über die Bundesregierung',
      answer_c: 'bei Diskussionen über Religionen',
      answer_d: 'bei Kritik am Staat'
    },
    question_17: {
      question: 'Die deutschen Gesetze verbieten ...',
      answer_a: 'Meinungsfreiheit der Einwohnerinnen und Einwohner.',
      answer_b: 'Petitionen der Bürgerinnen und Bürger.',
      answer_c: 'Versammlungsfreiheit der Einwohnerinnen und Einwohner.',
      answer_d: 'Ungleichbehandlung der Bürgerinnen und Bürger durch den Staat.'
    },
    question_18: {
      question: 'Welches Grundrecht ist in Artikel 1 des Grundgesetzes der Bundesrepublik Deutschland garantiert?',
      answer_a: 'die Unantastbarkeit der Menschenwürde',
      answer_b: 'das Recht auf Leben',
      answer_c: 'Religionsfreiheit',
      answer_d: 'Meinungsfreiheit'
    },
    question_19: {
      question: 'Was versteht man unter dem Recht der "Freizügigkeit" in Deutschland?',
      answer_a: 'Man darf sich seinen Wohnort selbst aussuchen.',
      answer_b: 'Man kann seinen Beruf wechseln.',
      answer_c: 'Man darf sich für eine andere Religion entscheiden.',
      answer_d: 'Man darf sich in der Öffentlichkeit nur leicht bekleidet bewegen.'
    },
    question_20: {
      question: 'Eine Partei in Deutschland verfolgt das Ziel, eine Diktatur zu errichten. Sie ist dann ...',
      answer_a: 'tolerant.',
      answer_b: 'rechtsstaatlich orientiert.',
      answer_c: 'gesetzestreu.',
      answer_d: 'verfassungswidrig.'
    },
    question_21: {
      question: 'Welches ist das Wappen der Bundesrepublik Deutschland?',
      answer_a: 'Bild 1',
      answer_b: 'Bild 2',
      answer_c: 'Bild 3',
      answer_d: 'Bild 4'
    },
    question_22: {
      question: 'Was für eine Staatsform hat Deutschland?',
      answer_a: 'Monarchie',
      answer_b: 'Diktatur',
      answer_c: 'Republik',
      answer_d: 'Fürstentum'
    },
    question_23: {
      question: 'In Deutschland sind die meisten Erwerbstätigen ...',
      answer_a: 'in kleinen Familienunternehmen beschäftigt.',
      answer_b: 'ehrenamtlich für ein Bundesland tätig.',
      answer_c: 'selbstständig mit einer eigenen Firma tätig.',
      answer_d: 'bei einer Firma oder Behörde beschäftigt.'
    },
    question_24: {
      question: 'Wie viele Bundesländer hat die Bundesrepublik Deutschland?',
      answer_a: '14',
      answer_b: '15',
      answer_c: '16',
      answer_d: '17'
    },
    question_25: {
      question: 'Was ist kein Bundesland der Bundesrepublik Deutschland?',
      answer_a: 'Elsass-Lothringen',
      answer_b: 'Nordrhein-Westfalen',
      answer_c: 'Mecklenburg-Vorpommern',
      answer_d: 'Sachsen-Anhalt'
    },
    question_26: {
      question: 'Deutschland ist ...',
      answer_a: 'eine kommunistische Republik.',
      answer_b: 'ein demokratischer und sozialer Bundesstaat.',
      answer_c: 'eine kapitalistische und soziale Monarchie.',
      answer_d: 'ein sozialer und sozialistischer Bundesstaat.'
    },
    question_27: {
      question: 'Deutschland ist ...',
      answer_a: 'ein sozialistischer Staat.',
      answer_b: 'ein Bundesstaat.',
      answer_c: 'eine Diktatur.',
      answer_d: 'eine Monarchie.'
    },
    question_28: {
      question: 'Wer wählt in Deutschland die Abgeordneten zum Bundestag?',
      answer_a: 'das Militär',
      answer_b: 'die Wirtschaft',
      answer_c: 'das wahlberechtigte Volk',
      answer_d: 'die Verwaltung'
    },
    question_29: {
      question: 'Welches Tier ist das Wappentier der Bundesrepublik Deutschland?',
      answer_a: 'Löwe',
      answer_b: 'Adler',
      answer_c: 'Bär',
      answer_d: 'Pferd'
    },
    question_30: {
      question: 'Was ist kein Merkmal unserer Demokratie?',
      answer_a: 'regelmäßige Wahlen',
      answer_b: 'Pressezensur',
      answer_c: 'Meinungsfreiheit',
      answer_d: 'verschiedene Parteien'
    },
    question_31: {
      question: 'Die Zusammenarbeit von Parteien zur Bildung einer Regierung nennt man in Deutschland ...',
      answer_a: 'Einheit.',
      answer_b: 'Koalition.',
      answer_c: 'Ministerium.',
      answer_d: 'Fraktion.'
    },
    question_32: {
      question: 'Was ist keine staatliche Gewalt in Deutschland?',
      answer_a: 'Gesetzgebung',
      answer_b: 'Regierung',
      answer_c: 'Presse',
      answer_d: 'Rechtsprechung'
    },
    question_33: {
      question: 'Welche Aussage ist richtig? In Deutschland ...',
      answer_a: 'sind Staat und Religionsgemeinschaften voneinander getrennt.',
      answer_b: 'bilden die Religionsgemeinschaften den Staat.',
      answer_c: 'ist der Staat abhängig von den Religionsgemeinschaften.',
      answer_d: 'bilden Staat und Religionsgemeinschaften eine Einheit.'
    },
    question_34: {
      question: 'Was ist Deutschland nicht?',
      answer_a: 'eine Demokratie',
      answer_b: 'ein Rechtsstaat',
      answer_c: 'eine Monarchie',
      answer_d: 'ein Sozialstaat'
    },
    question_35: {
      question: 'Womit finanziert der deutsche Staat die Sozialversicherung?',
      answer_a: 'Kirchensteuer',
      answer_b: 'Sozialabgaben',
      answer_c: 'Spendengeldern',
      answer_d: 'Vereinsbeiträgen'
    },
    question_36: {
      question: 'Welche Maßnahme schafft in Deutschland soziale Sicherheit?',
      answer_a: 'die Krankenversicherung',
      answer_b: 'die Autoversicherung',
      answer_c: 'die Gebäudeversicherung',
      answer_d: 'die Haftpflichtversicherung'
    },
    question_37: {
      question: 'Wie werden die Regierungschefinnen/Regierungschefs der meisten Bundesländer in Deutschland genannt?',
      answer_a: 'Erste Ministerin/Erster Minister',
      answer_b: 'Premierministerin/Premierminister',
      answer_c: 'Senatorin/Senator',
      answer_d: 'Ministerpräsidentin/Ministerpräsident'
    },
    question_38: {
      question: 'Die Bundesrepublik Deutschland ist ein demokratischer und sozialer ...',
      answer_a: 'Staatenverbund.',
      answer_b: 'Bundesstaat.',
      answer_c: 'Staatenbund.',
      answer_d: 'Zentralstaat.'
    },
    question_39: {
      question: 'Was hat jedes deutsche Bundesland?',
      answer_a: 'eine eigene Außenministerin/einen eigenen Außenminister',
      answer_b: 'eine eigene Währung',
      answer_c: 'eine eigene Armee',
      answer_d: 'eine eigene Regierung'
    },
    question_40: {
      question: 'Mit welchen Worten beginnt die deutsche Nationalhymne?',
      answer_a: 'Völker, hört die Signale ...',
      answer_b: 'Einigkeit und Recht und Freiheit ...',
      answer_c: 'Freude schöner Götterfunken ...',
      answer_d: 'Deutschland einig Vaterland ...'
    },
    question_41: {
      question: 'Warum gibt es in einer Demokratie mehr als eine Partei?',
      answer_a: 'weil dadurch die unterschiedlichen Meinungen der Bürgerinnen und Bürger vertreten werden',
      answer_b: 'damit Bestechung in der Politik begrenzt wird',
      answer_c: 'um politische Demonstrationen zu verhindern',
      answer_d: 'um wirtschaftlichen Wettbewerb anzuregen'
    },
    question_42: {
      question: 'Wer beschließt in Deutschland ein neues Gesetz?',
      answer_a: 'die Regierung',
      answer_b: 'das Parlament',
      answer_c: 'die Gerichte',
      answer_d: 'die Polizei'
    },
    question_43: {
      question: 'Wann kann in Deutschland eine Partei verboten werden?',
      answer_a: 'wenn ihr Wahlkampf zu teuer ist',
      answer_b: 'wenn sie gegen die Verfassung kämpft',
      answer_c: 'wenn sie Kritik am Staatsoberhaupt äußert',
      answer_d: 'wenn ihr Programm eine neue Richtung vorschlägt'
    },
    question_44: {
      question: 'Wen kann man als Bürgerin/Bürger in Deutschland nicht direkt wählen?',
      answer_a: 'Abgeordnete des EU-Parlaments',
      answer_b: 'Die Bundespräsidentin/den Bundespräsidenten',
      answer_c: 'Landtagsabgeordnete',
      answer_d: 'Bundestagsabgeordnete'
    },
    question_45: {
      question: 'Zu welcher Versicherung gehört die Pflegeversicherung?',
      answer_a: 'Sozialversicherung',
      answer_b: 'Unfallversicherung',
      answer_c: 'Hausratsversicherung',
      answer_d: 'Haftpflicht- und Feuerversicherung'
    },
    question_46: {
      question: 'Der deutsche Staat hat viele Aufgaben. Welche Aufgabe gehört dazu?',
      answer_a: 'Er baut Straßen und Schulen.',
      answer_b: 'Er verkauft Lebensmittel und Kleidung.',
      answer_c: 'Er versorgt alle Einwohnerinnen und Einwohner kostenlos mit Zeitungen.',
      answer_d: 'Er produziert Autos und Busse.'
    },
    question_47: {
      question: 'Der deutsche Staat hat viele Aufgaben. Welche Aufgabe gehört nicht dazu?',
      answer_a: 'Er bezahlt für alle Staatsangehörigen Urlaubsreisen.',
      answer_b: 'Er zahlt Kindergeld.',
      answer_c: 'Er unterstützt Museen.',
      answer_d: 'Er fördert Sportlerinnen und Sportler.'
    },
    question_48: {
      question: 'Welches Organ gehört nicht zu den Verfassungsorganen Deutschlands?',
      answer_a: 'der Bundesrat',
      answer_b: 'die Bundespräsidentin/der Bundespräsident',
      answer_c: 'die Bürgerversammlung',
      answer_d: 'die Regierung'
    },
    question_49: {
      question: 'Wer bestimmt in Deutschland die Schulpolitik?',
      answer_a: 'die Lehrer und Lehrerinnen',
      answer_b: 'die Bundesländer',
      answer_c: 'das Familienministerium',
      answer_d: 'die Universitäten'
    },
    question_50: {
      question: 'Die Wirtschaftsform in Deutschland nennt man ...',
      answer_a: 'freie Zentralwirtschaft.',
      answer_b: 'soziale Marktwirtschaft.',
      answer_c: 'gelenkte Zentralwirtschaft.',
      answer_d: 'Planwirtschaft.'
    },
    question_51: {
      question: 'Zu einem demokratischen Rechtsstaat gehört es nicht, dass ...',
      answer_a: 'Menschen sich kritisch über die Regierung äußern können.',
      answer_b: 'Bürger friedlich demonstrieren gehen dürfen.',
      answer_c: 'Menschen von einer Privatpolizei ohne Grund verhaftet werden.',
      answer_d: 'jemand ein Verbrechen begeht und deshalb verhaftet wird.'
    },
    question_52: {
      question: 'Was bedeutet "Volkssouveränität"? Alle Staatsgewalt geht vom ...',
      answer_a: 'Volke aus.',
      answer_b: 'Bundestag aus.',
      answer_c: 'preußischen König aus.',
      answer_d: 'Bundesverfassungsgericht aus.'
    },
    question_53: {
      question: 'Was bedeutet "Rechtsstaat" in Deutschland?',
      answer_a: 'Der Staat hat Recht.',
      answer_b: 'Es gibt nur rechte Parteien.',
      answer_c: 'Die Bürgerinnen und Bürger entscheiden über Gesetze.',
      answer_d: 'Der Staat muss die Gesetze einhalten.'
    },
    question_54: {
      question: 'Was ist keine staatliche Gewalt in Deutschland?',
      answer_a: 'Legislative',
      answer_b: 'Judikative',
      answer_c: 'Exekutive',
      answer_d: 'Direktive'
    },
    question_55: {
      question: 'Was zeigt dieses Bild?',
      answer_a: 'den Bundestagssitz in Berlin',
      answer_b: 'das Bundesverfassungsgericht in Karlsruhe',
      answer_c: 'das Bundesratsgebäude in Berlin',
      answer_d: 'das Bundeskanzleramt in Berlin'
    },
    question_56: {
      question: 'Welches Amt gehört in Deutschland zur Gemeindeverwaltung?',
      answer_a: 'Pfarramt',
      answer_b: 'Ordnungsamt',
      answer_c: 'Finanzamt',
      answer_d: 'Auswärtiges Amt'
    },
    question_57: {
      question: 'Wer wird meistens zur Präsidentin/zum Präsidenten des Deutschen Bundestages gewählt?',
      answer_a: 'die/der älteste Abgeordnete im Parlament',
      answer_b: 'die Ministerpräsidentin/der Ministerpräsident des größten Bundeslandes',
      answer_c: 'eine ehemalige Bundeskanzlerin/ein ehemaliger Bundeskanzler',
      answer_d: 'eine Abgeordnete/ein Abgeordneter der stärksten Fraktion'
    },
    question_58: {
      question: 'Wer ernennt in Deutschland die Ministerinnen/die Minister der Bundesregierung?',
      answer_a: 'die Präsidentin/der Präsident des Bundesverfassungsgerichtes',
      answer_b: 'die Bundespräsidentin/der Bundespräsident',
      answer_c: 'die Bundesratspräsidentin/der Bundesratspräsident',
      answer_d: 'die Bundestagspräsidentin/der Bundestagspräsident'
    },
    question_59: {
      question:
        'Vor wie vielen Jahren gab es erstmals eine jüdische Gemeinde auf dem Gebiet des heutigen Deutschlands?',
      answer_a: 'vor etwa 300 Jahren',
      answer_b: 'vor etwa 700 Jahren',
      answer_c: 'vor etwa 1150 Jahren',
      answer_d: 'vor etwa 1700 Jahren'
    },
    question_60: {
      question: 'In Deutschland gehören der Bundestag und der Bundesrat zur ...',
      answer_a: 'Exekutive.',
      answer_b: 'Legislative.',
      answer_c: 'Direktive.',
      answer_d: 'Judikative.'
    },
    question_61: {
      question: 'Was bedeutet "Volkssouveränität"?',
      answer_a: 'Die Königin/der König herrscht über das Volk.',
      answer_b: 'Das Bundesverfassungsgericht steht über der Verfassung.',
      answer_c: 'Die Interessenverbände üben die Souveränität zusammen mit der Regierung aus.',
      answer_d: 'Die Staatsgewalt geht vom Volke aus.'
    },
    question_62: {
      question: 'Wenn das Parlament eines deutschen Bundeslandes gewählt wird, nennt man das ...',
      answer_a: 'Kommunalwahl',
      answer_b: 'Landtagswahl',
      answer_c: 'Europawahl',
      answer_d: 'Bundestagswahl'
    },
    question_63: {
      question: 'Was gehört in Deutschland nicht zur Exekutive?',
      answer_a: 'die Polizei',
      answer_b: 'die Gerichte',
      answer_c: 'das Finanzamt',
      answer_d: 'die Ministerien'
    },
    question_64: {
      question: 'Die Bundesrepublik Deutschland ist heute gegliedert in ...',
      answer_a: 'vier Besatzungszonen.',
      answer_b: 'einen Oststaat und einen Weststaat.',
      answer_c: '16 Kantone.',
      answer_d: 'Bund, Länder und Kommunen.'
    },
    question_65: {
      question: 'Es gehört nicht zu den Aufgaben des Deutschen Bundestages, ...',
      answer_a: 'Gesetze zu entwerfen.',
      answer_b: 'die Bundesregierung zu kontrollieren.',
      answer_c: 'die Bundeskanzlerin/den Bundeskanzler zu wählen.',
      answer_d: 'das Bundeskabinett zu bilden.'
    },
    question_66: {
      question: 'Welche Städte haben die größten jüdischen Gemeinden in Deutschland?',
      answer_a: 'Berlin und München',
      answer_b: 'Hamburg und Essen',
      answer_c: 'Nürnberg und Stuttgart',
      answer_d: 'Worms und Speyer'
    },
    question_67: {
      question: 'Was ist in Deutschland vor allem eine Aufgabe der Bundesländer?',
      answer_a: 'Verteidigungspolitik',
      answer_b: 'Außenpolitik',
      answer_c: 'Wirtschaftspolitik',
      answer_d: 'Schulpolitik'
    },
    question_68: {
      question: 'Warum kontrolliert der Staat in Deutschland das Schulwesen?',
      answer_a: 'weil es in Deutschland nur staatliche Schulen gibt',
      answer_b: 'weil alle Schülerinnen und Schüler einen Schulabschluss haben müssen',
      answer_c: 'weil es in den Bundesländern verschiedene Schulen gibt',
      answer_d: 'weil es nach dem Grundgesetz seine Aufgabe ist'
    },
    question_69: {
      question:
        'Die Bundesrepublik Deutschland hat einen dreistufigen Verwaltungsaufbau. Wie heißt die unterste politische Stufe?',
      answer_a: 'Stadträte',
      answer_b: 'Landräte',
      answer_c: 'Gemeinden',
      answer_d: 'Bezirksämter'
    },
    question_70: {
      question:
        'Der deutsche Bundespräsident Gustav Heinemann gibt Helmut Schmidt 1974 die Ernennungsurkunde zum deutschen Bundeskanzler. Was gehört zu den Aufgaben der deutschen Bundespräsidentin/des deutschen Bundespräsidenten?',
      answer_a: 'Sie/Er führt die Regierungsgeschäfte.',
      answer_b: 'Sie/Er kontrolliert die Regierungspartei.',
      answer_c: 'Sie/Er wählt die Ministerinnen/Minister aus.',
      answer_d: 'Sie/Er schlägt die Kanzlerin/den Kanzler zur Wahl vor.'
    },
    question_71: {
      question:
        'Wo hält sich die deutsche Bundeskanzlerin/der deutsche Bundeskanzler am häufigsten auf? Am häufigsten ist sie/er ...',
      answer_a: 'in Bonn, weil sich dort das Bundeskanzleramt und der Bundestag befinden.',
      answer_b: 'auf Schloss Meseberg, dem Gästehaus der Bundesregierung, um Staatsgäste zu empfangen.',
      answer_c:
        'auf Schloss Bellevue, dem Amtssitz der Bundespräsidentin/des Bundespräsidenten, um Staatsgäste zu empfangen.',
      answer_d: 'in Berlin, weil sich dort das Bundeskanzleramt und der Bundestag befinden.'
    },
    question_72: {
      question: 'Wie heißt die jetzige Bundeskanzlerin/der jetzige Bundeskanzler von Deutschland?',
      answer_a: 'Gerhard Schröder',
      answer_b: 'Angela Merkel',
      answer_c: 'Ursula von der Leyen',
      answer_d: 'Friedrich Merz'
    },
    question_73: {
      question: 'Die beiden größten Fraktionen im Deutschen Bundestag heißen zurzeit ...',
      answer_a: 'CDU/CSU und AfD.',
      answer_b: 'Die Linke und Bündnis 90/Die Grünen.',
      answer_c: 'Bündnis 90/Die Grünen und SPD.',
      answer_d: 'Die Linke und CDU/CSU.'
    },
    question_74: {
      question: 'Wie heißt das Parlament für ganz Deutschland?',
      answer_a: 'Bundesversammlung',
      answer_b: 'Volkskammer',
      answer_c: 'Bundestag',
      answer_d: 'Bundesgerichtshof'
    },
    question_75: {
      question: 'Wie heißt Deutschlands heutiges Staatsoberhaupt?',
      answer_a: 'Frank-Walter Steinmeier',
      answer_b: 'Bärbel Bas',
      answer_c: 'Bodo Ramelow',
      answer_d: 'Joachim Gauck'
    },
    question_76: {
      question: 'Was bedeutet die Abkürzung CDU in Deutschland?',
      answer_a: 'Christliche Deutsche Union',
      answer_b: 'Club Deutscher Unternehmer',
      answer_c: 'Christlicher Deutscher Umweltschutz',
      answer_d: 'Christlich Demokratische Union'
    },
    question_77: {
      question: 'Was ist die Bundeswehr?',
      answer_a: 'die deutsche Polizei',
      answer_b: 'ein deutscher Hafen',
      answer_c: 'eine deutsche Bürgerinitiative',
      answer_d: 'die deutsche Armee'
    },
    question_78: {
      question: 'Was bedeutet die Abkürzung SPD?',
      answer_a: 'Sozialistische Partei Deutschlands',
      answer_b: 'Sozialpolitische Partei Deutschlands',
      answer_c: 'Sozialdemokratische Partei Deutschlands',
      answer_d: 'Sozialgerechte Partei Deutschlands'
    },
    question_79: {
      question: 'Was bedeutet die Abkürzung FDP in Deutschland?',
      answer_a: 'Friedliche Demonstrative Partei',
      answer_b: 'Freie Deutschland Partei',
      answer_c: 'Führende Demokratische Partei',
      answer_d: 'Freie Demokratische Partei'
    },
    question_80: {
      question: 'Welches Gericht in Deutschland ist zuständig für die Auslegung des Grundgesetzes?',
      answer_a: 'Oberlandesgericht',
      answer_b: 'Amtsgericht',
      answer_c: 'Bundesverfassungsgericht',
      answer_d: 'Verwaltungsgericht'
    },
    question_81: {
      question: 'Wer wählt die Bundeskanzlerin/den Bundeskanzler in Deutschland?',
      answer_a: 'der Bundesrat',
      answer_b: 'die Bundesversammlung',
      answer_c: 'das Volk',
      answer_d: 'der Bundestag'
    },
    question_82: {
      question: 'Wer leitet das deutsche Bundeskabinett?',
      answer_a: 'die Bundestagspräsidentin/der Bundestagspräsident',
      answer_b: 'die Bundespräsidentin/der Bundespräsident',
      answer_c: 'die Bundesratspräsidentin/der Bundesratspräsident',
      answer_d: 'die Bundeskanzlerin/der Bundeskanzler'
    },
    question_83: {
      question: 'Wer wählt die deutsche Bundeskanzlerin/den deutschen Bundeskanzler?',
      answer_a: 'das Volk',
      answer_b: 'die Bundesversammlung',
      answer_c: 'der Bundestag',
      answer_d: 'die Bundesregierung'
    },
    question_84: {
      question: 'Welche Hauptaufgabe hat die deutsche Bundespräsidentin/der deutsche Bundespräsident? Sie/Er ...',
      answer_a: 'regiert das Land.',
      answer_b: 'entwirft die Gesetze.',
      answer_c: 'repräsentiert das Land.',
      answer_d: 'überwacht die Einhaltung der Gesetze.'
    },
    question_85: {
      question: 'Wer bildet den deutschen Bundesrat?',
      answer_a: 'die Abgeordneten des Bundestages',
      answer_b: 'die Ministerinnen und Minister der Bundesregierung',
      answer_c: 'die Regierungsvertreter der Bundesländer',
      answer_d: 'die Parteimitglieder'
    },
    question_86: {
      question: 'Wer wählt in Deutschland die Bundespräsidentin/den Bundespräsidenten?',
      answer_a: 'die Bundesversammlung',
      answer_b: 'der Bundesrat',
      answer_c: 'das Bundesparlament',
      answer_d: 'das Bundesverfassungsgericht'
    },
    question_87: {
      question: 'Wer ist das Staatsoberhaupt der Bundesrepublik Deutschland?',
      answer_a: 'die Bundeskanzlerin/der Bundeskanzler',
      answer_b: 'die Bundespräsidentin/der Bundespräsident',
      answer_c: 'die Bundesratspräsidentin/der Bundesratspräsident',
      answer_d: 'die Bundestagspräsidentin/der Bundestagspräsident'
    },
    question_88: {
      question: 'Die parlamentarische Opposition im Deutschen Bundestag ...',
      answer_a: 'kontrolliert die Regierung.',
      answer_b: 'entscheidet, wer Bundesministerin/Bundesminister wird.',
      answer_c: 'bestimmt, wer im Bundesrat sitzt.',
      answer_d: 'schlägt die Regierungschefinnen/Regierungschefs der Länder vor.'
    },
    question_89: {
      question: 'Wie nennt man in Deutschland die Vereinigung von Abgeordneten einer Partei im Parlament?',
      answer_a: 'Verband',
      answer_b: 'Ältestenrat',
      answer_c: 'Fraktion',
      answer_d: 'Opposition'
    },
    question_90: {
      question: 'Die deutschen Bundesländer wirken an der Gesetzgebung des Bundes mit durch ...',
      answer_a: 'den Bundesrat.',
      answer_b: 'die Bundesversammlung.',
      answer_c: 'den Bundestag.',
      answer_d: 'die Bundesregierung.'
    },
    question_91: {
      question:
        'In Deutschland kann ein Regierungswechsel in einem Bundesland Auswirkungen auf die Bundespolitik haben. Das Regieren wird ...',
      answer_a: 'schwieriger, wenn sich dadurch die Mehrheit im Bundestag ändert.',
      answer_b: 'leichter, wenn dadurch neue Parteien in den Bundesrat kommen.',
      answer_c: 'schwieriger, wenn dadurch die Mehrheit im Bundesrat verändert wird.',
      answer_d: 'leichter, wenn es sich um ein reiches Bundesland handelt.'
    },
    question_92: {
      question: 'Was bedeutet die Abkürzung CSU in Deutschland?',
      answer_a: 'Christlich Sichere Union',
      answer_b: 'Christlich Süddeutsche Union',
      answer_c: 'Christlich Sozialer Unternehmerverband',
      answer_d: 'Christlich Soziale Union'
    },
    question_93: {
      question: 'Je mehr "Zweitstimmen" eine Partei bei einer Bundestagswahl bekommt, desto ...',
      answer_a: 'weniger Erststimmen kann sie haben.',
      answer_b: 'mehr Direktkandidaten der Partei ziehen ins Parlament ein.',
      answer_c: 'größer ist das Risiko, eine Koalition bilden zu müssen.',
      answer_d: 'mehr Sitze erhält die Partei im Parlament.'
    },
    question_94: {
      question: 'Ab welchem Alter darf man in Deutschland an der Wahl zum Deutschen Bundestag teilnehmen?',
      answer_a: '16',
      answer_b: '18',
      answer_c: '21',
      answer_d: '23'
    },
    question_95: {
      question: 'Was gilt für die meisten Kinder in Deutschland?',
      answer_a: 'Wahlpflicht',
      answer_b: 'Schulpflicht',
      answer_c: 'Schweigepflicht',
      answer_d: 'Religionspflicht'
    },
    question_96: {
      question: 'Wie kann jemand, der den Holocaust leugnet, bestraft werden?',
      answer_a: 'Kürzung sozialer Leistungen',
      answer_b: 'bis zu 100 Sozialstunden',
      answer_c: 'gar nicht, Holocaustleugnung ist erlaubt',
      answer_d: 'mit Freiheitsstrafe bis zu fünf Jahren oder mit Geldstrafe'
    },
    question_97: {
      question: 'Was bezahlt man in Deutschland automatisch, wenn man fest angestellt ist?',
      answer_a: 'Sozialversicherung',
      answer_b: 'Sozialhilfe',
      answer_c: 'Kindergeld',
      answer_d: 'Wohngeld'
    },
    question_98: {
      question: 'Wenn Abgeordnete im Deutschen Bundestag ihre Fraktion wechseln, ...',
      answer_a: 'dürfen sie nicht mehr an den Sitzungen des Parlaments teilnehmen.',
      answer_b: 'kann die Regierung ihre Mehrheit verlieren.',
      answer_c: 'muss die Bundespräsidentin/der Bundespräsident zuvor ihr/sein Einverständnis geben.',
      answer_d: 'dürfen die Wählerinnen/Wähler dieser Abgeordneten noch einmal wählen.'
    },
    question_99: {
      question: 'Wer bezahlt in Deutschland die Sozialversicherungen?',
      answer_a: 'Arbeitgeberinnen/Arbeitgeber und Arbeitnehmerinnen/Arbeitnehmer',
      answer_b: 'nur Arbeitnehmerinnen/Arbeitnehmer',
      answer_c: 'alle Staatsangehörigen',
      answer_d: 'nur Arbeitgeberinnen/Arbeitgeber'
    },
    question_100: {
      question: 'Was gehört nicht zur gesetzlichen Sozialversicherung?',
      answer_a: 'die Lebensversicherung',
      answer_b: 'die gesetzliche Rentenversicherung',
      answer_c: 'die Arbeitslosenversicherung',
      answer_d: 'die Pflegeversicherung'
    },
    question_101: {
      question: 'Gewerkschaften sind Interessenverbände der ...',
      answer_a: 'Jugendlichen.',
      answer_b: 'Arbeitnehmerinnen und Arbeitnehmer.',
      answer_c: 'Rentnerinnen und Rentner.',
      answer_d: 'Arbeitgeberinnen und Arbeitgeber.'
    },
    question_102: {
      question:
        'Womit kann man in der Bundesrepublik Deutschland geehrt werden, wenn man auf politischem, wirtschaftlichem, kulturellem, geistigem oder sozialem Gebiet eine besondere Leistung erbracht hat? Mit dem ...',
      answer_a: 'Bundesverdienstkreuz',
      answer_b: 'Bundesadler',
      answer_c: 'Vaterländischen Verdienstorden',
      answer_d: 'Ehrentitel "Held der Deutschen Demokratischen Republik"'
    },
    question_103: {
      question: 'Was wird in Deutschland als "Ampelkoalition" bezeichnet? Die Zusammenarbeit ...',
      answer_a: 'der Bundestagsfraktionen von CDU und CSU',
      answer_b: 'von SPD, FDP und Bündnis 90/Die Grünen in einer Regierung',
      answer_c: 'von CSU, Die LINKE und Bündnis 90/Die Grünen in einer Regierung',
      answer_d: 'der Bundestagsfraktionen von CDU und SPD'
    },
    question_104: {
      question: 'Eine Frau in Deutschland verliert ihre Arbeit. Was darf nicht der Grund für diese Entlassung sein?',
      answer_a: 'Die Frau ist lange krank und arbeitsunfähig.',
      answer_b: 'Die Frau kam oft zu spät zur Arbeit.',
      answer_c: 'Die Frau erledigt private Sachen während der Arbeitszeit.',
      answer_d: 'Die Frau bekommt ein Kind und ihr Chef weiß das.'
    },
    question_105: {
      question: 'Was ist eine Aufgabe von Wahlhelferinnen/Wahlhelfern in Deutschland?',
      answer_a: 'Sie helfen alten Menschen bei der Stimmabgabe in der Wahlkabine.',
      answer_b: 'Sie schreiben die Wahlbenachrichtigungen vor der Wahl.',
      answer_c: 'Sie geben Zwischenergebnisse an die Medien weiter.',
      answer_d: 'Sie zählen die Stimmen nach dem Ende der Wahl.'
    },
    question_106: {
      question:
        'In Deutschland helfen ehrenamtliche Wahlhelferinnen und Wahlhelfer bei den Wahlen. Was ist eine Aufgabe von Wahlhelferinnen/Wahlhelfern?',
      answer_a: 'Sie helfen Kindern und alten Menschen beim Wählen.',
      answer_b: 'Sie schreiben Karten und Briefe mit der Angabe des Wahllokals.',
      answer_c: 'Sie geben Zwischenergebnisse an Journalisten weiter.',
      answer_d: 'Sie zählen die Stimmen nach dem Ende der Wahl.'
    },
    question_107: {
      question: 'Für wie viele Jahre wird der Bundestag in Deutschland gewählt?',
      answer_a: '2 Jahre',
      answer_b: '4 Jahre',
      answer_c: '6 Jahre',
      answer_d: '8 Jahre'
    },
    question_108: {
      question: 'Bei einer Bundestagswahl in Deutschland darf jede/jeder wählen, die/der ...',
      answer_a: 'in der Bundesrepublik Deutschland wohnt und wählen möchte.',
      answer_b: 'Bürgerin/Bürger der Bundesrepublik Deutschland ist und mindestens 18 Jahre alt ist.',
      answer_c: 'seit mindestens 3 Jahren in der Bundesrepublik Deutschland lebt.',
      answer_d: 'Bürgerin/Bürger der Bundesrepublik Deutschland ist und mindestens 21 Jahre alt ist.'
    },
    question_109: {
      question: 'Wie oft gibt es normalerweise Bundestagswahlen in Deutschland?',
      answer_a: 'alle drei Jahre',
      answer_b: 'alle vier Jahre',
      answer_c: 'alle fünf Jahre',
      answer_d: 'alle sechs Jahre'
    },
    question_110: {
      question: 'Für wie viele Jahre wird der Bundestag in Deutschland gewählt?',
      answer_a: '2 Jahre',
      answer_b: '3 Jahre',
      answer_c: '4 Jahre',
      answer_d: '5 Jahre'
    },
    question_111: {
      question: 'Welche Handlungen mit Bezug auf den Staat Israel sind in Deutschland verboten?',
      answer_a: 'die Politik Israels öffentlich kritisieren',
      answer_b: 'das Aufhängen einer israelischen Flagge auf dem Privatgrundstück',
      answer_c: 'eine Diskussion über die Politik Israels',
      answer_d: 'der öffentliche Aufruf zur Vernichtung Israels'
    },
    question_112: {
      question: 'Die Wahlen in Deutschland sind ...',
      answer_a: 'speziell.',
      answer_b: 'geheim.',
      answer_c: 'berufsbezogen.',
      answer_d: 'geschlechtsabhängig.'
    },
    question_113: {
      question: 'Wahlen in Deutschland gewinnt die Partei, die ...',
      answer_a: 'die meisten Stimmen bekommt.',
      answer_b: 'die meisten Männer mehrheitlich gewählt haben.',
      answer_c: 'die meisten Stimmen bei den Arbeiterinnen/Arbeitern bekommen hat.',
      answer_d: 'die meisten Erststimmen für ihre Kanzlerkandidatin/ihren Kanzlerkandidaten erhalten hat.'
    },
    question_114: {
      question: 'An demokratischen Wahlen in Deutschland teilzunehmen ist ...',
      answer_a: 'eine Pflicht.',
      answer_b: 'ein Recht.',
      answer_c: 'ein Zwang.',
      answer_d: 'eine Last.'
    },
    question_115: {
      question: 'Was bedeutet "aktives Wahlrecht" in Deutschland?',
      answer_a: 'Man kann gewählt werden.',
      answer_b: 'Man muss wählen gehen.',
      answer_c: 'Man kann wählen.',
      answer_d: 'Man muss zur Auszählung der Stimmen gehen.'
    },
    question_116: {
      question: 'Wenn Sie bei einer Bundestagswahl in Deutschland wählen dürfen, heißt das ...',
      answer_a: 'aktive Wahlkampagne.',
      answer_b: 'aktives Wahlverfahren.',
      answer_c: 'aktiver Wahlkampf.',
      answer_d: 'aktives Wahlrecht.'
    },
    question_117: {
      question:
        'Wie viel Prozent der Zweitstimmen müssen Parteien mindestens bekommen, um in den Deutschen Bundestag gewählt zu werden?',
      answer_a: '3%',
      answer_b: '4%',
      answer_c: '5%',
      answer_d: '6%'
    },
    question_118: {
      question: 'Wer darf bei den rund 40 jüdischen Makkabi-Sportvereinen Mitglied werden?',
      answer_a: 'nur Deutsche',
      answer_b: 'nur Israelis',
      answer_c: 'nur religiöse Menschen',
      answer_d: 'alle Menschen'
    },
    question_119: {
      question: 'Wahlen in Deutschland sind frei. Was bedeutet das?',
      answer_a: 'Alle verurteilten Straftäterinnen/Straftäter dürfen nicht wählen.',
      answer_b: 'Wenn ich wählen gehen möchte, muss meine Arbeitgeberin/mein Arbeitgeber mir frei geben.',
      answer_c: 'Jede Person kann ohne Zwang entscheiden, ob sie wählen möchte und wen sie wählen möchte.',
      answer_d: 'Ich kann frei entscheiden, wo ich wählen gehen möchte.'
    },
    question_120: {
      question: 'Das Wahlsystem in Deutschland ist ein ...',
      answer_a: 'Zensuswahlrecht.',
      answer_b: 'Dreiklassenwahlrecht.',
      answer_c: 'Mehrheits- und Verhältniswahlrecht.',
      answer_d: 'allgemeines Männerwahlrecht.'
    },
    question_121: {
      question:
        'Eine Partei möchte in den Deutschen Bundestag. Sie muss aber einen Mindestanteil an Wählerstimmen haben. Das heißt ...',
      answer_a: '5%-Hürde.',
      answer_b: 'Zulassungsgrenze.',
      answer_c: 'Basiswert.',
      answer_d: 'Richtlinie.'
    },
    question_122: {
      question: 'Welchem Grundsatz unterliegen Wahlen in Deutschland? Wahlen in Deutschland sind ...',
      answer_a: 'frei, gleich, geheim.',
      answer_b: 'offen, sicher, frei.',
      answer_c: 'geschlossen, gleich, sicher.',
      answer_d: 'sicher, offen, freiwillig.'
    },
    question_123: {
      question: 'Was ist in Deutschland die "5%-Hürde"?',
      answer_a: 'Abstimmungsregelung im Bundestag für kleine Parteien',
      answer_b: 'Anwesenheitskontrolle im Bundestag für Abstimmungen',
      answer_c: 'Mindestanteil an Wählerstimmen, um ins Parlament zu kommen',
      answer_d: 'Anwesenheitskontrolle im Bundesrat für Abstimmungen'
    },
    question_124: {
      question: 'Die Bundestagswahl in Deutschland ist die Wahl ...',
      answer_a: 'der Bundeskanzlerin/des Bundeskanzlers.',
      answer_b: 'der Parlamente der Länder.',
      answer_c: 'des Parlaments für Deutschland.',
      answer_d: 'der Bundespräsidentin/des Bundespräsidenten.'
    },
    question_125: {
      question: 'In einer Demokratie ist eine Funktion von regelmäßigen Wahlen, ...',
      answer_a: 'die Bürgerinnen und Bürger zu zwingen, ihre Stimme abzugeben.',
      answer_b: 'nach dem Willen der Wählermehrheit den Wechsel der Regierung zu ermöglichen.',
      answer_c: 'im Land bestehende Gesetze beizubehalten.',
      answer_d: 'den Armen mehr Macht zu geben.'
    },
    question_126: {
      question: 'Was bekommen wahlberechtigte Bürgerinnen und Bürger in Deutschland vor einer Wahl?',
      answer_a: 'eine Wahlbenachrichtigung von der Gemeinde',
      answer_b: 'eine Wahlerlaubnis von der Bundespräsidentin/von dem Bundespräsidenten',
      answer_c: 'eine Benachrichtigung von der Bundesversammlung',
      answer_d: 'eine Benachrichtigung vom Pfarramt'
    },
    question_127: {
      question: 'Warum gibt es die 5%-Hürde im Wahlgesetz der Bundesrepublik Deutschland? Es gibt sie, weil ...',
      answer_a: 'die Programme von vielen kleinen Parteien viele Gemeinsamkeiten haben.',
      answer_b: 'die Bürgerinnen und Bürger bei vielen kleinen Parteien die Orientierung verlieren können.',
      answer_c: 'viele kleine Parteien die Regierungsbildung erschweren.',
      answer_d: 'die kleinen Parteien nicht so viel Geld haben, um die Politikerinnen und Politiker zu bezahlen.'
    },
    question_128: {
      question: 'Parlamentsmitglieder, die von den Bürgerinnen und Bürgern gewählt werden, nennt man ...',
      answer_a: 'Abgeordnete.',
      answer_b: 'Kanzlerinnen/Kanzler.',
      answer_c: 'Botschafterinnen/Botschafter.',
      answer_d: 'Ministerpräsidentinnen/Ministerpräsidenten.'
    },
    question_129: {
      question: 'Vom Volk gewählt wird in Deutschland ...',
      answer_a: 'die Bundeskanzlerin/der Bundeskanzler.',
      answer_b: 'die Ministerpräsidentin/der Ministerpräsident eines Bundeslandes.',
      answer_c: 'der Bundestag.',
      answer_d: 'die Bundespräsidentin/der Bundespräsident.'
    },
    question_130: {
      question:
        'Welcher Stimmzettel wäre bei einer Bundestagswahl gültig? In Anlehnung an Bundeswahlordnung (BWO), Anlage 26',
      answer_a: '1',
      answer_b: '2',
      answer_c: '3',
      answer_d: '4'
    },
    question_131: {
      question: 'In Deutschland ist eine Bürgermeisterin/ein Bürgermeister ...',
      answer_a: 'die Leiterin/der Leiter einer Schule.',
      answer_b: 'die Chefin/der Chef einer Bank.',
      answer_c: 'das Oberhaupt einer Gemeinde.',
      answer_d: 'die/der Vorsitzende einer Partei.'
    },
    question_132: {
      question: 'Viele Menschen in Deutschland arbeiten in ihrer Freizeit ehrenamtlich. Was bedeutet das?',
      answer_a: 'Sie arbeiten als Soldatinnen/Soldaten.',
      answer_b: 'Sie arbeiten freiwillig und unbezahlt in Vereinen und Verbänden.',
      answer_c: 'Sie arbeiten in der Bundesregierung.',
      answer_d: 'Sie arbeiten in einem Krankenhaus und verdienen dabei Geld.'
    },
    question_133: {
      question: 'Was ist bei Bundestags- und Landtagswahlen in Deutschland erlaubt?',
      answer_a: 'Der Ehemann wählt für seine Frau mit.',
      answer_b: 'Man kann durch Briefwahl seine Stimme abgeben.',
      answer_c: 'Man kann am Wahltag telefonisch seine Stimme abgeben.',
      answer_d: 'Kinder ab dem Alter von 14 Jahren dürfen wählen.'
    },
    question_134: {
      question:
        'Man will die Buslinie abschaffen, mit der Sie immer zur Arbeit fahren. Was können Sie machen, um die Buslinie zu erhalten?',
      answer_a:
        'Ich beteilige mich an einer Bürgerinitiative für die Erhaltung der Buslinie oder gründe selber eine Initiative.',
      answer_b: 'Ich werde Mitglied in einem Sportverein und trainiere Radfahren.',
      answer_c:
        'Ich wende mich an das Finanzamt, weil ich als Steuerzahlerin/Steuerzahler ein Recht auf die Buslinie habe.',
      answer_d: 'Ich schreibe einen Brief an das Forstamt der Gemeinde.'
    },
    question_135: {
      question: 'Wen vertreten die Gewerkschaften in Deutschland?',
      answer_a: 'große Unternehmen',
      answer_b: 'kleine Unternehmen',
      answer_c: 'Selbstständige',
      answer_d: 'Arbeitnehmerinnen und Arbeitnehmer'
    },
    question_136: {
      question: 'Sie gehen in Deutschland zum Arbeitsgericht bei ...',
      answer_a: 'falscher Nebenkostenabrechnung.',
      answer_b: 'ungerechtfertigter Kündigung durch Ihre Chefin/Ihren Chef.',
      answer_c: 'Problemen mit den Nachbarinnen/Nachbarn.',
      answer_d: 'Schwierigkeiten nach einem Verkehrsunfall.'
    },
    question_137: {
      question: 'Welches Gericht ist in Deutschland bei Konflikten in der Arbeitswelt zuständig?',
      answer_a: 'das Familiengericht',
      answer_b: 'das Strafgericht',
      answer_c: 'das Arbeitsgericht',
      answer_d: 'das Amtsgericht'
    },
    question_138: {
      question:
        'Was kann ich in Deutschland machen, wenn mir meine Arbeitgeberin/mein Arbeitgeber zu Unrecht gekündigt hat?',
      answer_a: 'weiterarbeiten und freundlich zur Chefin/zum Chef sein',
      answer_b: 'ein Mahnverfahren gegen die Arbeitgeberin/den Arbeitgeber führen',
      answer_c: 'Kündigungsschutzklage erheben',
      answer_d: 'die Arbeitgeberin/den Arbeitgeber bei der Polizei anzeigen'
    },
    question_139: {
      question: 'Wann kommt es in Deutschland zu einem Prozess vor Gericht? Wenn jemand ...',
      answer_a: 'zu einer anderen Religion übertritt.',
      answer_b: 'eine Straftat begangen hat und angeklagt wird.',
      answer_c: 'eine andere Meinung als die der Regierung vertritt.',
      answer_d: 'sein Auto falsch geparkt hat und es abgeschleppt wird.'
    },
    question_140: {
      question: 'Was macht eine Schöffin/ein Schöffe in Deutschland? Sie/Er ...',
      answer_a: 'entscheidet mit Richterinnen/Richtern über Schuld und Strafe.',
      answer_b: 'gibt Bürgerinnen/Bürgern rechtlichen Rat.',
      answer_c: 'stellt Urkunden aus.',
      answer_d: 'verteidigt die Angeklagte/den Angeklagten.'
    },
    question_141: {
      question: 'Wer berät in Deutschland Personen bei Rechtsfragen und vertritt sie vor Gericht?',
      answer_a: 'eine Rechtsanwältin/ein Rechtsanwalt',
      answer_b: 'eine Richterin/ein Richter',
      answer_c: 'eine Schöffin/ein Schöffe',
      answer_d: 'eine Staatsanwältin/ein Staatsanwalt'
    },
    question_142: {
      question:
        'Was ist die Hauptaufgabe einer Richterin/eines Richters in Deutschland? Eine Richterin/ein Richter ...',
      answer_a: 'vertritt Bürgerinnen und Bürger vor einem Gericht.',
      answer_b: 'arbeitet an einem Gericht und spricht Urteile.',
      answer_c: 'ändert Gesetze.',
      answer_d: 'betreut Jugendliche vor Gericht.'
    },
    question_143: {
      question: 'Eine Richterin/ein Richter in Deutschland gehört zur ...',
      answer_a: 'Judikative.',
      answer_b: 'Exekutive.',
      answer_c: 'Operative.',
      answer_d: 'Legislative.'
    },
    question_144: {
      question: 'Eine Richterin/ein Richter gehört in Deutschland zur ...',
      answer_a: 'vollziehenden Gewalt.',
      answer_b: 'rechtsprechenden Gewalt.',
      answer_c: 'planenden Gewalt.',
      answer_d: 'gesetzgebenden Gewalt.'
    },
    question_145: {
      question:
        'In Deutschland wird die Staatsgewalt geteilt. Für welche Staatsgewalt arbeitet eine Richterin/ein Richter? Für die ...',
      answer_a: 'Judikative',
      answer_b: 'Exekutive',
      answer_c: 'Presse',
      answer_d: 'Legislative'
    },
    question_146: {
      question: 'Wie nennt man in Deutschland ein Verfahren vor einem Gericht?',
      answer_a: 'Programm',
      answer_b: 'Prozedur',
      answer_c: 'Protokoll',
      answer_d: 'Prozess'
    },
    question_147: {
      question: 'Was ist die Arbeit einer Richterin/eines Richters in Deutschland?',
      answer_a: 'Deutschland regieren',
      answer_b: 'Recht sprechen',
      answer_c: 'Pläne erstellen',
      answer_d: 'Gesetze erlassen'
    },
    question_148: {
      question: 'Was ist eine Aufgabe der Polizei in Deutschland?',
      answer_a: 'das Land zu verteidigen',
      answer_b: 'die Bürgerinnen und Bürger abzuhören',
      answer_c: 'die Gesetze zu beschließen',
      answer_d: 'die Einhaltung von Gesetzen zu überwachen'
    },
    question_149: {
      question: 'Was ist ein Beispiel für antisemitisches Verhalten?',
      answer_a: 'ein jüdisches Fest besuchen',
      answer_b: 'die israelische Regierung kritisieren',
      answer_c: 'den Holocaust leugnen',
      answer_d: 'gegen Juden Fußball spielen.'
    },
    question_150: {
      question: 'Eine Gerichtsschöffin/ein Gerichtsschöffe in Deutschland ist ...',
      answer_a: 'die Stellvertreterin/der Stellvertreter des Stadtoberhaupts.',
      answer_b: 'eine ehrenamtliche Richterin/ein ehrenamtlicher Richter.',
      answer_c: 'ein Mitglied eines Gemeinderats.',
      answer_d: 'eine Person, die Jura studiert hat.'
    },
    question_151: {
      question: 'Wer baute die Mauer in Berlin?',
      answer_a: 'Großbritannien',
      answer_b: 'die DDR',
      answer_c: 'die Bundesrepublik Deutschland',
      answer_d: 'die USA'
    },
    question_152: {
      question: 'Wann waren die Nationalsozialisten mit Adolf Hitler in Deutschland an der Macht?',
      answer_a: '1918 bis 1923',
      answer_b: '1932 bis 1950',
      answer_c: '1933 bis 1945',
      answer_d: '1945 bis 1989'
    },
    question_153: {
      question: 'Was war am 8. Mai 1945?',
      answer_a: 'Tod Adolf Hitlers',
      answer_b: 'Beginn des Berliner Mauerbaus',
      answer_c: 'Wahl von Konrad Adenauer zum Bundeskanzler',
      answer_d: 'Ende des Zweiten Weltkriegs in Europa'
    },
    question_154: {
      question: 'Wann war der Zweite Weltkrieg zu Ende?',
      answer_a: '1933',
      answer_b: '1945',
      answer_c: '1949',
      answer_d: '1961'
    },
    question_155: {
      question: 'Wann waren die Nationalsozialisten in Deutschland an der Macht?',
      answer_a: '1888 bis 1918',
      answer_b: '1921 bis 1934',
      answer_c: '1933 bis 1945',
      answer_d: '1949 bis 1963'
    },
    question_156: {
      question: 'In welchem Jahr wurde Hitler Reichskanzler?',
      answer_a: '1923',
      answer_b: '1927',
      answer_c: '1933',
      answer_d: '1936'
    },
    question_157: {
      question: 'Die Nationalsozialisten mit Adolf Hitler errichteten 1933 in Deutschland ...',
      answer_a: 'eine Diktatur.',
      answer_b: 'einen demokratischen Staat.',
      answer_c: 'eine Monarchie.',
      answer_d: 'ein Fürstentum.'
    },
    question_158: {
      question: 'Das "Dritte Reich" war eine ...',
      answer_a: 'Diktatur.',
      answer_b: 'Demokratie.',
      answer_c: 'Monarchie.',
      answer_d: 'Räterepublik.'
    },
    question_159: {
      question: 'Was gab es in Deutschland nicht während der Zeit des Nationalsozialismus?',
      answer_a: 'freie Wahlen',
      answer_b: 'Pressezensur',
      answer_c: 'willkürliche Verhaftungen',
      answer_d: 'Verfolgung von Juden'
    },
    question_160: {
      question: 'Welcher Krieg dauerte von 1939 bis 1945?',
      answer_a: 'der Erste Weltkrieg',
      answer_b: 'der Zweite Weltkrieg',
      answer_c: 'der Vietnamkrieg',
      answer_d: 'der Golfkrieg'
    },
    question_161: {
      question: 'Was kennzeichnete den NS-Staat? Eine Politik ...',
      answer_a: 'des staatlichen Rassismus',
      answer_b: 'der Meinungsfreiheit',
      answer_c: 'der allgemeinen Religionsfreiheit',
      answer_d: 'der Entwicklung der Demokratie'
    },
    question_162: {
      question: 'Claus Schenk Graf von Stauffenberg wurde bekannt durch ...',
      answer_a: 'eine Goldmedaille bei den Olympischen Spielen 1936.',
      answer_b: 'den Bau des Reichstagsgebäudes.',
      answer_c: 'den Aufbau der Wehrmacht.',
      answer_d: 'das Attentat auf Hitler am 20. Juli 1944.'
    },
    question_163: {
      question: 'In welchem Jahr zerstörten die Nationalsozialisten Synagogen und jüdische Geschäfte in Deutschland?',
      answer_a: '1925',
      answer_b: '1930',
      answer_c: '1938',
      answer_d: '1945'
    },
    question_164: {
      question: 'Was passierte am 9. November 1938 in Deutschland?',
      answer_a: 'Mit dem Angriff auf Polen beginnt der Zweite Weltkrieg.',
      answer_b: 'Die Nationalsozialisten verlieren eine Wahl und lösen den Reichstag auf.',
      answer_c: 'Jüdische Geschäfte und Synagogen werden durch Nationalsozialisten und ihre Anhänger zerstört.',
      answer_d: 'Hitler wird Reichspräsident und lässt alle Parteien verbieten.'
    },
    question_165: {
      question: 'Wie hieß der erste Bundeskanzler der Bundesrepublik Deutschland?',
      answer_a: 'Konrad Adenauer',
      answer_b: 'Kurt Georg Kiesinger',
      answer_c: 'Helmut Schmidt',
      answer_d: 'Willy Brandt'
    },
    question_166: {
      question: 'Bei welchen Demonstrationen in Deutschland riefen die Menschen "Wir sind das Volk"?',
      answer_a: 'beim Arbeiteraufstand 1953 in der DDR',
      answer_b: 'bei den Demonstrationen 1968 in der Bundesrepublik Deutschland',
      answer_c: 'bei den Anti-Atomkraft-Demonstrationen 1985 in der Bundesrepublik Deutschland',
      answer_d: 'bei den Montagsdemonstrationen 1989 in der DDR'
    },
    question_167: {
      question:
        'Welche Länder wurden nach dem Zweiten Weltkrieg in Deutschland als "Alliierte Besatzungsmächte" bezeichnet?',
      answer_a: 'Sowjetunion, Großbritannien, Polen, Schweden',
      answer_b: 'Frankreich, Sowjetunion, Italien, Japan',
      answer_c: 'USA, Sowjetunion, Spanien, Portugal',
      answer_d: 'USA, Sowjetunion, Großbritannien, Frankreich'
    },
    question_168: {
      question: 'Welches Land war keine "Alliierte Besatzungsmacht" in Deutschland?',
      answer_a: 'USA',
      answer_b: 'Sowjetunion',
      answer_c: 'Frankreich',
      answer_d: 'Japan'
    },
    question_169: {
      question: 'Wann wurde die Bundesrepublik Deutschland gegründet?',
      answer_a: '1939',
      answer_b: '1945',
      answer_c: '1949',
      answer_d: '1951'
    },
    question_170: {
      question: 'Was gab es während der Zeit des Nationalsozialismus in Deutschland?',
      answer_a: 'das Verbot von Parteien',
      answer_b: 'das Recht zur freien Entfaltung der Persönlichkeit',
      answer_c: 'Pressefreiheit',
      answer_d: 'den Schutz der Menschenwürde'
    },
    question_171: {
      question: 'Soziale Marktwirtschaft bedeutet, die Wirtschaft ...',
      answer_a: 'steuert sich allein nach Angebot und Nachfrage.',
      answer_b: 'wird vom Staat geplant und gesteuert, Angebot und Nachfrage werden nicht berücksichtigt.',
      answer_c: 'richtet sich nach der Nachfrage im Ausland.',
      answer_d: 'richtet sich nach Angebot und Nachfrage, aber der Staat sorgt für einen sozialen Ausgleich.'
    },
    question_172: {
      question: 'In welcher Besatzungszone wurde die DDR gegründet? In der ...',
      answer_a: 'amerikanischen Besatzungszone',
      answer_b: 'französischen Besatzungszone',
      answer_c: 'britischen Besatzungszone',
      answer_d: 'sowjetischen Besatzungszone'
    },
    question_173: {
      question: 'Die Bundesrepublik Deutschland ist ein Gründungsmitglied ...',
      answer_a: 'des Nordatlantikpakts (NATO).',
      answer_b: 'der Vereinten Nationen (VN).',
      answer_c: 'der Europäischen Union (EU).',
      answer_d: 'des Warschauer Pakts.'
    },
    question_174: {
      question: 'Wann wurde die DDR gegründet?',
      answer_a: '1947',
      answer_b: '1949',
      answer_c: '1953',
      answer_d: '1956'
    },
    question_175: {
      question: 'Wie viele Besatzungszonen gab es in Deutschland nach dem Zweiten Weltkrieg?',
      answer_a: '3',
      answer_b: '4',
      answer_c: '5',
      answer_d: '6'
    },
    question_176: {
      question: 'Wie waren die Besatzungszonen Deutschlands nach 1945 verteilt?',
      answer_a: '1 =Großbritannien, 2=Sowjetunion, 3=Frankreich, 4=USA',
      answer_b: '1=Sowjetunion, 2=Großbritannien, 3=USA, 4=Frankreich',
      answer_c: '1=Großbritannien, 2=Sowjetunion, 3=USA, 4=Frankreich',
      answer_d: '1=Großbritannien, 2=USA, 3=Sowjetunion, 4=Frankreich'
    },
    question_177: {
      question: 'Welche deutsche Stadt wurde nach dem Zweiten Weltkrieg in vier Sektoren aufgeteilt?',
      answer_a: 'München',
      answer_b: 'Berlin',
      answer_c: 'Dresden',
      answer_d: 'Frankfurt/Oder'
    },
    question_178: {
      question:
        'Vom Juni 1948 bis zum Mai 1949 wurden die Bürgerinnen und Bürger von West-Berlin durch eine Luftbrücke versorgt. Welcher Umstand war dafür verantwortlich?',
      answer_a: 'Für Frankreich war eine Versorgung der West-Berliner Bevölkerung mit dem Flugzeug kostengünstiger.',
      answer_b: 'Die amerikanischen Soldatinnen und Soldaten hatten beim Landtransport Angst vor Überfällen.',
      answer_c: 'Für Großbritannien war die Versorgung über die Luftbrücke schneller.',
      answer_d: 'Die Sowjetunion unterbrach den gesamten Verkehr auf dem Landwege.'
    },
    question_179: {
      question: 'Wie endete der Zweite Weltkrieg in Europa offiziell?',
      answer_a: 'mit dem Tod Adolf Hitlers',
      answer_b: 'durch die bedingungslose Kapitulation Deutschlands',
      answer_c: 'mit dem Rückzug der Deutschen aus den besetzten Gebieten',
      answer_d: 'durch eine Revolution in Deutschland'
    },
    question_180: {
      question: 'Der erste Bundeskanzler der Bundesrepublik Deutschland war ...',
      answer_a: 'Ludwig Erhard.',
      answer_b: 'Willy Brandt.',
      answer_c: 'Konrad Adenauer.',
      answer_d: 'Gerhard Schröder.'
    },
    question_181: {
      question:
        'Was wollte Willy Brandt mit seinem Kniefall 1970 im ehemaligen jüdischen Ghetto in Warschau ausdrücken?',
      answer_a: 'Er hat sich den ehemaligen Alliierten unterworfen.',
      answer_b: 'Er bat Polen und die polnischen Juden um Vergebung.',
      answer_c: 'Er zeigte seine Demut vor dem Warschauer Pakt.',
      answer_d: 'Er sprach ein Gebet am Grab des Unbekannten Soldaten.'
    },
    question_182: {
      question: 'Wie heißt das jüdische Gebetshaus?',
      answer_a: 'Basilika',
      answer_b: 'Moschee',
      answer_c: 'Synagoge',
      answer_d: 'Kirche'
    },
    question_183: {
      question: 'Wann war in der Bundesrepublik Deutschland das "Wirtschaftswunder"?',
      answer_a: '40er Jahre',
      answer_b: '50er Jahre',
      answer_c: '70er Jahre',
      answer_d: '80er Jahre'
    },
    question_184: {
      question: 'Auf welcher rechtlichen Grundlage wurde der Staat Israel gegründet?',
      answer_a: 'eine Resolution der Vereinten Nationen',
      answer_b: 'ein Beschluss des Zionistenkongresses',
      answer_c: 'ein Vorschlag der Bundesregierung',
      answer_d: 'ein Vorschlag der UdSSR'
    },
    question_185: {
      question: 'Wofür stand der Ausdruck "Eiserner Vorhang"? Für die Abschottung ...',
      answer_a: 'des Warschauer Pakts gegen den Westen',
      answer_b: 'Norddeutschlands gegen Süddeutschland',
      answer_c: 'Nazi-Deutschlands gegen die Alliierten',
      answer_d: 'Europas gegen die USA'
    },
    question_186: {
      question:
        'Im Jahr 1953 gab es in der DDR einen Aufstand, an den lange Zeit in der Bundesrepublik Deutschland ein Feiertag erinnerte. Wann war das?',
      answer_a: '1. Mai',
      answer_b: '17. Juni',
      answer_c: '20. Juli',
      answer_d: '9. November'
    },
    question_187: {
      question: 'Welcher deutsche Staat hatte eine schwarz-rot-goldene Flagge mit Hammer, Zirkel und Ährenkranz?',
      answer_a: 'Preußen',
      answer_b: 'Bundesrepublik Deutschland',
      answer_c: '"Drittes Reich"',
      answer_d: 'DDR'
    },
    question_188: {
      question: 'In welchem Jahr wurde die Mauer in Berlin gebaut?',
      answer_a: '1953',
      answer_b: '1956',
      answer_c: '1959',
      answer_d: '1961'
    },
    question_189: {
      question: 'Wann baute die DDR die Mauer in Berlin?',
      answer_a: '1919',
      answer_b: '1933',
      answer_c: '1961',
      answer_d: '1990'
    },
    question_190: {
      question: 'Was bedeutet die Abkürzung DDR?',
      answer_a: 'Dritter Deutscher Rundfunk',
      answer_b: 'Die Deutsche Republik',
      answer_c: 'Dritte Deutsche Republik',
      answer_d: 'Deutsche Demokratische Republik'
    },
    question_191: {
      question: 'Wann wurde die Mauer in Berlin für alle geöffnet?',
      answer_a: '1987',
      answer_b: '1989',
      answer_c: '1992',
      answer_d: '1995'
    },
    question_192: {
      question: 'Welches heutige deutsche Bundesland gehörte früher zum Gebiet der DDR?',
      answer_a: 'Brandenburg',
      answer_b: 'Bayern',
      answer_c: 'Saarland',
      answer_d: 'Hessen'
    },
    question_193: {
      question: 'Von 1961 bis 1989 war Berlin ...',
      answer_a: 'ohne Bürgermeister.',
      answer_b: 'ein eigener Staat.',
      answer_c: 'durch eine Mauer geteilt.',
      answer_d: 'nur mit dem Flugzeug erreichbar.'
    },
    question_194: {
      question: 'Am 3. Oktober feiert man in Deutschland den Tag der Deutschen ...',
      answer_a: 'Einheit.',
      answer_b: 'Nation.',
      answer_c: 'Bundesländer.',
      answer_d: 'Städte.'
    },
    question_195: {
      question: 'Welches heutige deutsche Bundesland gehörte früher zum Gebiet der DDR?',
      answer_a: 'Hessen',
      answer_b: 'Sachsen-Anhalt',
      answer_c: 'Nordrhein-Westfalen',
      answer_d: 'Saarland'
    },
    question_196: {
      question:
        'Warum nennt man die Zeit im Herbst 1989 in der DDR "Die Wende"? In dieser Zeit veränderte sich die DDR politisch ...',
      answer_a: 'von einer Diktatur zur Demokratie.',
      answer_b: 'von einer liberalen Marktwirtschaft zum Sozialismus.',
      answer_c: 'von einer Monarchie zur Sozialdemokratie.',
      answer_d: 'von einem religiösen Staat zu einem kommunistischen Staat.'
    },
    question_197: {
      question: 'Welches heutige deutsche Bundesland gehörte früher zum Gebiet der DDR?',
      answer_a: 'Thüringen',
      answer_b: 'Hessen',
      answer_c: 'Bayern',
      answer_d: 'Bremen'
    },
    question_198: {
      question: 'Welches heutige deutsche Bundesland gehörte früher zum Gebiet der DDR?',
      answer_a: 'Bayern',
      answer_b: 'Niedersachsen',
      answer_c: 'Sachsen',
      answer_d: 'Baden-Württemberg'
    },
    question_199: {
      question: 'Mit der Abkürzung "Stasi" meinte man in der DDR ...',
      answer_a: 'das Parlament.',
      answer_b: 'das Ministerium für Staatssicherheit.',
      answer_c: 'eine regierende Partei.',
      answer_d: 'das Ministerium für Volksbildung.'
    },
    question_200: {
      question: 'Welches heutige deutsche Bundesland gehörte früher zum Gebiet der DDR?',
      answer_a: 'Hessen',
      answer_b: 'Schleswig-Holstein',
      answer_c: 'Mecklenburg-Vorpommern',
      answer_d: 'Saarland'
    },
    question_201: {
      question: 'Welche der folgenden Auflistungen enthält nur Bundesländer, die zum Gebiet der früheren DDR gehörten?',
      answer_a: 'Niedersachsen, Nordrhein-Westfalen, Hessen, Schleswig-Holstein, Brandenburg',
      answer_b: 'Mecklenburg-Vorpommern, Brandenburg, Sachsen, Sachsen-Anhalt, Thüringen',
      answer_c: 'Bayern, Baden-Württemberg, Rheinland-Pfalz, Thüringen, Sachsen',
      answer_d: 'Sachsen, Thüringen, Hessen, Niedersachen, Brandenburg'
    },
    question_202: {
      question: 'Zu wem gehörte die DDR im "Kalten Krieg"?',
      answer_a: 'zu den Westmächten',
      answer_b: 'zum Warschauer Pakt',
      answer_c: 'zur NATO',
      answer_d: 'zu den blockfreien Staaten'
    },
    question_203: {
      question: 'Wie hieß das Wirtschaftssystem der DDR?',
      answer_a: 'Marktwirtschaft',
      answer_b: 'Planwirtschaft',
      answer_c: 'Angebot und Nachfrage',
      answer_d: 'Kapitalismus'
    },
    question_204: {
      question: 'Wie wurden die Bundesrepublik Deutschland und die DDR zu einem Staat?',
      answer_a: 'Die Bundesrepublik hat die DDR besetzt.',
      answer_b: 'Die heutigen fünf östlichen Bundesländer sind der Bundesrepublik Deutschland beigetreten.',
      answer_c: 'Die westlichen Bundesländer sind der DDR beigetreten.',
      answer_d: 'Die DDR hat die Bundesrepublik Deutschland besetzt.'
    },
    question_205: {
      question: 'Mit dem Beitritt der DDR zur Bundesrepublik Deutschland gehören die neuen Bundesländer nun auch ...',
      answer_a: 'zur Europäischen Union.',
      answer_b: 'zum Warschauer Pakt.',
      answer_c: 'zur OPEC.',
      answer_d: 'zur Europäischen Verteidigungsgemeinschaft.'
    },
    question_206: {
      question: 'Woran erinnern die sogenannten „Stolpersteine“ in Deutschland?',
      answer_a: 'an berühmte deutsche Politikerinnen und Politiker',
      answer_b: 'an die Opfer des Nationalsozialismus',
      answer_c: 'an Verkehrstote',
      answer_d: 'an bekannte jüdische Musiker'
    },
    question_207: {
      question: 'In welchem Militärbündnis war die DDR Mitglied?',
      answer_a: 'in der NATO',
      answer_b: 'im Rheinbund',
      answer_c: 'im Warschauer Pakt',
      answer_d: 'im Europabündnis'
    },
    question_208: {
      question: 'Was war die "Stasi"?',
      answer_a: 'der Geheimdienst im "Dritten Reich"',
      answer_b: 'eine berühmte deutsche Gedenkstätte',
      answer_c: 'der Geheimdienst der DDR',
      answer_d: 'ein deutscher Sportverein während des Zweiten Weltkrieges'
    },
    question_209: {
      question: 'Welches war das Wappen der Deutschen Demokratischen Republik?',
      answer_a: 'Bild 1',
      answer_b: 'Bild 2',
      answer_c: 'Bild 3',
      answer_d: 'Bild 4'
    },
    question_210: {
      question: 'Was ereignete sich am 17. Juni 1953 in der DDR?',
      answer_a: 'der feierliche Beitritt zum Warschauer Pakt',
      answer_b: 'landesweite Streiks und ein Volksaufstand',
      answer_c: 'der 1. SED-Parteitag',
      answer_d: 'der erste Besuch Fidel Castros'
    },
    question_211: {
      question: 'Welcher Politiker steht für die "Ostverträge"?',
      answer_a: 'Helmut Kohl',
      answer_b: 'Willy Brandt',
      answer_c: 'Michail Gorbatschow',
      answer_d: 'Ludwig Erhard'
    },
    question_212: {
      question: 'Wie heißt Deutschland mit vollem Namen?',
      answer_a: 'Bundesstaat Deutschland',
      answer_b: 'Bundesländer Deutschland',
      answer_c: 'Bundesrepublik Deutschland',
      answer_d: 'Bundesbezirk Deutschland'
    },
    question_213: {
      question: 'Wie viele Einwohner hat Deutschland?',
      answer_a: '70 Millionen',
      answer_b: '78 Millionen',
      answer_c: '84 Millionen',
      answer_d: '90 Millionen'
    },
    question_214: {
      question: 'Welche Farben hat die deutsche Flagge?',
      answer_a: 'schwarz-rot-gold',
      answer_b: 'rot-weiß-schwarz',
      answer_c: 'schwarz-rot-grün',
      answer_d: 'schwarz-gelb-rot'
    },
    question_215: {
      question: 'Wer wird als "Kanzler der Deutschen Einheit" bezeichnet?',
      answer_a: 'Gerhard Schröder',
      answer_b: 'Helmut Kohl',
      answer_c: 'Konrad Adenauer',
      answer_d: 'Helmut Schmidt'
    },
    question_216: {
      question: 'Welches Symbol ist im Plenarsaal des Deutschen Bundestages zu sehen?',
      answer_a: 'der Bundesadler',
      answer_b: 'die Fahne der Stadt Berlin',
      answer_c: 'der Reichsadler',
      answer_d: 'die Reichskrone'
    },
    question_217: {
      question: 'In welchem Zeitraum gab es die Deutsche Demokratische Republik (DDR)?',
      answer_a: '1919 bis 1927',
      answer_b: '1933 bis 1945',
      answer_c: '1945 bis 1961',
      answer_d: '1949 bis 1990'
    },
    question_218: {
      question: 'Wie viele Bundesländer kamen bei der Wiedervereinigung 1990 zur Bundesrepublik Deutschland hinzu?',
      answer_a: '4',
      answer_b: '5',
      answer_c: '6',
      answer_d: '7'
    },
    question_219: {
      question: 'Die Bundesrepublik Deutschland hat die Grenzen von heute seit ...',
      answer_a: '1933',
      answer_b: '1949',
      answer_c: '1971',
      answer_d: '1990'
    },
    question_220: {
      question: 'Der 27. Januar ist in Deutschland ein offizieller Gedenktag. Woran erinnert dieser Tag?',
      answer_a: 'an das Ende des Zweiten Weltkrieges',
      answer_b: 'an die Verabschiedung des Grundgesetzes',
      answer_c: 'an die Wiedervereinigung Deutschlands',
      answer_d: 'an die Opfer des Nationalsozialismus (Tag der Befreiung des Vernichtungslagers Auschwitz)'
    },
    question_221: {
      question: 'Deutschland ist Mitglied des Schengener Abkommens. Was bedeutet das?',
      answer_a: 'Deutsche können in viele Länder Europas ohne Passkontrolle reisen.',
      answer_b: 'Alle Menschen können ohne Personenkontrolle in Deutschland einreisen.',
      answer_c: 'Deutsche können ohne Passkontrolle in jedes Land reisen.',
      answer_d: 'Deutsche können in jedem Land mit dem Euro bezahlen.'
    },
    question_222: {
      question: 'Welches Land ist ein Nachbarland von Deutschland?',
      answer_a: 'Ungarn',
      answer_b: 'Portugal',
      answer_c: 'Spanien',
      answer_d: 'Schweiz'
    },
    question_223: {
      question: 'Welches Land ist ein Nachbarland von Deutschland?',
      answer_a: 'Rumänien',
      answer_b: 'Bulgarien',
      answer_c: 'Polen',
      answer_d: 'Griechenland'
    },
    question_224: {
      question: 'Was bedeutet die Abkürzung EU?',
      answer_a: 'Europäische Unternehmen',
      answer_b: 'Europäische Union',
      answer_c: 'Einheitliche Union',
      answer_d: 'Euro Union'
    },
    question_225: {
      question: 'In welchem anderen Land gibt es eine große deutschsprachige Bevölkerung?',
      answer_a: 'Tschechien',
      answer_b: 'Norwegen',
      answer_c: 'Spanien',
      answer_d: 'Österreich'
    },
    question_226: {
      question: 'Welche ist die Flagge der Europäischen Union?',
      answer_a: 'Bild 1',
      answer_b: 'Bild 2',
      answer_c: 'Bild 3',
      answer_d: 'Bild 4'
    },
    question_227: {
      question: 'Welches Land ist ein Nachbarland von Deutschland?',
      answer_a: 'Finnland',
      answer_b: 'Dänemark',
      answer_c: 'Norwegen',
      answer_d: 'Schweden'
    },
    question_228: {
      question: 'Wie wird der Beitritt der DDR zur Bundesrepublik Deutschland im Jahr 1990 allgemein genannt?',
      answer_a: 'NATO-Osterweiterung',
      answer_b: 'EU-Osterweiterung',
      answer_c: 'Deutsche Wiedervereinigung',
      answer_d: 'Europäische Gemeinschaft'
    },
    question_229: {
      question: 'Welches Land ist ein Nachbarland von Deutschland?',
      answer_a: 'Spanien',
      answer_b: 'Bulgarien',
      answer_c: 'Norwegen',
      answer_d: 'Luxemburg'
    },
    question_230: {
      question: 'Das Europäische Parlament wird regelmäßig gewählt, nämlich alle ...',
      answer_a: '5 Jahre.',
      answer_b: '6 Jahre.',
      answer_c: '7 Jahre.',
      answer_d: '8 Jahre.'
    },
    question_231: {
      question: 'Was bedeutet der Begriff "europäische Integration"?',
      answer_a: 'Damit sind amerikanische Einwanderinnen und Einwanderer in Europa gemeint.',
      answer_b: 'Der Begriff meint den Einwanderungsstopp nach Europa.',
      answer_c: 'Damit sind europäische Auswanderinnen und Auswanderer in den USA gemeint.',
      answer_d: 'Der Begriff meint den Zusammenschluss europäischer Staaten zur EU.'
    },
    question_232: {
      question: 'Wer wird bei der Europawahl gewählt?',
      answer_a: 'die Europäische Kommission',
      answer_b: 'die Länder, die in die EU eintreten dürfen',
      answer_c: 'die Abgeordneten des Europäischen Parlaments',
      answer_d: 'die europäische Verfassung'
    },
    question_233: {
      question: 'Welches Land ist ein Nachbarland von Deutschland?',
      answer_a: 'Tschechien',
      answer_b: 'Bulgarien',
      answer_c: 'Griechenland',
      answer_d: 'Portugal'
    },
    question_234: {
      question: 'Wo ist ein Sitz des Europäischen Parlaments?',
      answer_a: 'London',
      answer_b: 'Paris',
      answer_c: 'Berlin',
      answer_d: 'Straßburg'
    },
    question_235: {
      question:
        'Der damalige französische Staatspräsident François Mitterrand und der damalige deutsche Bundeskanzler Helmut Kohl gedenken in Verdun gemeinsam der Toten beider Weltkriege. Welches Ziel der Europäischen Union wird bei diesem Treffen deutlich?',
      answer_a: 'Freundschaft zwischen England und Deutschland',
      answer_b: 'Reisefreiheit in alle Länder der EU',
      answer_c: 'Frieden und Sicherheit in den Ländern der EU',
      answer_d: 'einheitliche Feiertage in den Ländern der EU'
    },
    question_236: {
      question: 'Wie viele Mitgliedstaaten hat die EU heute?',
      answer_a: '21',
      answer_b: '23',
      answer_c: '25',
      answer_d: '27'
    },
    question_237: {
      question:
        '2007 wurde das 50-jährige Jubiläum der "Römischen Verträge" gefeiert. Was war der Inhalt der Verträge?',
      answer_a: 'Beitritt Deutschlands zur NATO',
      answer_b: 'Gründung der Europäischen Wirtschaftsgemeinschaft (EWG)',
      answer_c: 'Verpflichtung Deutschlands zu Reparationsleistungen',
      answer_d: 'Festlegung der Oder-Neiße-Linie als Ostgrenze'
    },
    question_238: {
      question: 'An welchen Orten arbeitet das Europäische Parlament?',
      answer_a: 'Paris, London und Den Haag',
      answer_b: 'Straßburg, Luxemburg und Brüssel',
      answer_c: 'Rom, Bern und Wien',
      answer_d: 'Bonn, Zürich und Mailand'
    },
    question_239: {
      question:
        'Durch welche Verträge schloss sich die Bundesrepublik Deutschland mit anderen Staaten zur Europäischen Wirtschaftsgemeinschaft zusammen?',
      answer_a: 'durch die "Hamburger Verträge"',
      answer_b: 'durch die "Römischen Verträge"',
      answer_c: 'durch die "Pariser Verträge"',
      answer_d: 'durch die "Londoner Verträge"'
    },
    question_240: {
      question: 'Seit wann bezahlt man in Deutschland mit dem Euro in bar?',
      answer_a: '1995',
      answer_b: '1998',
      answer_c: '2002',
      answer_d: '2005'
    },
    question_241: {
      question: 'Frau Seger bekommt ein Kind. Was muss sie tun, um Elterngeld zu erhalten?',
      answer_a: 'Sie muss an ihre Krankenkasse schreiben.',
      answer_b: 'Sie muss einen Antrag bei der Elterngeldstelle stellen.',
      answer_c: 'Sie muss nichts tun, denn sie bekommt automatisch Elterngeld.',
      answer_d: 'Sie muss das Arbeitsamt um Erlaubnis bitten.'
    },
    question_242: {
      question: 'Wer entscheidet, ob ein Kind in Deutschland in den Kindergarten geht?',
      answer_a: 'der Staat',
      answer_b: 'die Bundesländer',
      answer_c: 'die Eltern/die Erziehungsberechtigten',
      answer_d: 'die Schulen'
    },
    question_243: {
      question:
        'Maik und Sybille wollen mit Freunden an ihrem deutschen Wohnort eine Demonstration auf der Straße abhalten. Was müssen sie vorher tun?',
      answer_a: 'Sie müssen die Demonstration anmelden.',
      answer_b: 'Sie müssen nichts tun. Man darf in Deutschland jederzeit überall demonstrieren.',
      answer_c: 'Sie können gar nichts tun, denn Demonstrationen sind in Deutschland grundsätzlich verboten.',
      answer_d: 'Maik und Sybille müssen einen neuen Verein gründen, weil nur Vereine demonstrieren dürfen.'
    },
    question_244: {
      question:
        'Welchen Schulabschluss braucht man normalerweise, um an einer Universität in Deutschland ein Studium zu beginnen?',
      answer_a: 'das Abitur',
      answer_b: 'ein Diplom',
      answer_c: 'die Prokura',
      answer_d: 'eine Gesellenprüfung'
    },
    question_245: {
      question: 'Wer darf in Deutschland nicht als Paar zusammenleben?',
      answer_a: 'Hans (20 Jahre) und Marie (19 Jahre)',
      answer_b: 'Tom (20 Jahre) und Klaus (45 Jahre)',
      answer_c: 'Sofie (35 Jahre) und Lisa (40 Jahre)',
      answer_d: 'Anne (13 Jahre) und Tim (25 Jahre)'
    },
    question_246: {
      question: 'Ab welchem Alter ist man in Deutschland volljährig?',
      answer_a: '16',
      answer_b: '18',
      answer_c: '19',
      answer_d: '21'
    },
    question_247: {
      question:
        'Eine Frau ist schwanger. Sie ist kurz vor und nach der Geburt ihres Kindes vom Gesetz besonders beschützt. Wie heißt dieser Schutz?',
      answer_a: 'Elternzeit',
      answer_b: 'Mutterschutz',
      answer_c: 'Geburtsvorbereitung',
      answer_d: 'Wochenbett'
    },
    question_248: {
      question: 'Die Erziehung der Kinder ist in Deutschland vor allem Aufgabe ...',
      answer_a: 'des Staates.',
      answer_b: 'der Eltern.',
      answer_c: 'der Großeltern.',
      answer_d: 'der Schulen.'
    },
    question_249: {
      question: 'Wer ist in Deutschland hauptsächlich verantwortlich für die Kindererziehung?',
      answer_a: 'der Staat',
      answer_b: 'die Eltern',
      answer_c: 'die Verwandten',
      answer_d: 'die Schulen'
    },
    question_250: {
      question: 'In Deutschland hat man die besten Chancen auf einen gut bezahlten Arbeitsplatz, wenn man ...',
      answer_a: 'katholisch ist.',
      answer_b: 'gut ausgebildet ist.',
      answer_c: 'eine Frau ist.',
      answer_d: 'Mitglied einer Partei ist.'
    },
    question_251: {
      question: 'Wenn man in Deutschland ein Kind schlägt, ...',
      answer_a: 'geht das niemanden etwas an.',
      answer_b: 'geht das nur die Familie etwas an.',
      answer_c: 'kann man dafür nicht bestraft werden.',
      answer_d: 'kann man dafür bestraft werden.'
    },
    question_252: {
      question: 'In Deutschland ...',
      answer_a: 'darf man zur gleichen Zeit nur mit einer Partnerin/einem Partner verheiratet sein.',
      answer_b: 'kann man mehrere Ehepartnerinnen/Ehepartner gleichzeitig haben.',
      answer_c: 'darf man nicht wieder heiraten, wenn man einmal verheiratet war.',
      answer_d: 'darf eine Frau nicht wieder heiraten, wenn ihr Mann gestorben ist.'
    },
    question_253: {
      question: 'Wo müssen Sie sich anmelden, wenn Sie in Deutschland umziehen?',
      answer_a: 'beim Einwohnermeldeamt',
      answer_b: 'beim Standesamt',
      answer_c: 'beim Ordnungsamt',
      answer_d: 'beim Gewerbeamt'
    },
    question_254: {
      question:
        'In Deutschland dürfen Ehepaare sich scheiden lassen. Meistens müssen sie dazu das "Trennungsjahr" einhalten. Was bedeutet das?',
      answer_a: 'Der Scheidungsprozess dauert ein Jahr.',
      answer_b: 'Die Ehegatten sind ein Jahr verheiratet, dann ist die Scheidung möglich.',
      answer_c: 'Das Besuchsrecht für die Kinder gilt ein Jahr.',
      answer_d: 'Die Ehegatten führen mindestens ein Jahr getrennt ihr eigenes Leben. Danach ist die Scheidung möglich.'
    },
    question_255: {
      question: 'Bei Erziehungsproblemen können Eltern in Deutschland Hilfe erhalten vom ...',
      answer_a: 'Ordnungsamt.',
      answer_b: 'Schulamt.',
      answer_c: 'Jugendamt.',
      answer_d: 'Gesundheitsamt.'
    },
    question_256: {
      question: 'Ein Ehepaar möchte in Deutschland ein Restaurant eröffnen. Was braucht es dazu unbedingt?',
      answer_a: 'eine Erlaubnis der Polizei',
      answer_b: 'eine Genehmigung einer Partei',
      answer_c: 'eine Genehmigung des Einwohnermeldeamts',
      answer_d: 'eine Gaststättenerlaubnis von der zuständigen Behörde'
    },
    question_257: {
      question: 'Eine erwachsene Frau möchte in Deutschland das Abitur nachholen. Das kann sie an ...',
      answer_a: 'einer Hochschule.',
      answer_b: 'einem Abendgymnasium.',
      answer_c: 'einer Hauptschule.',
      answer_d: 'einer Privatuniversität.'
    },
    question_258: {
      question: 'Was darf das Jugendamt in Deutschland?',
      answer_a: 'Es entscheidet, welche Schule das Kind besucht.',
      answer_b: 'Es kann ein Kind, das geschlagen wird oder hungern muss, aus der Familie nehmen.',
      answer_c: 'Es bezahlt das Kindergeld an die Eltern.',
      answer_d: 'Es kontrolliert, ob das Kind einen Kindergarten besucht.'
    },
    question_259: {
      question: 'Das Berufsinformationszentrum BIZ bei der Bundesagentur für Arbeit in Deutschland hilft bei der ...',
      answer_a: 'Rentenberechnung.',
      answer_b: 'Lehrstellensuche.',
      answer_c: 'Steuererklärung.',
      answer_d: 'Krankenversicherung.'
    },
    question_260: {
      question: 'In Deutschland hat ein Kind in der Schule ...',
      answer_a: 'Recht auf unbegrenzte Freizeit.',
      answer_b: 'Wahlfreiheit für alle Fächer.',
      answer_c: 'Anspruch auf Schulgeld.',
      answer_d: 'Anwesenheitspflicht.'
    },
    question_261: {
      question: 'Ein Mann möchte mit 30 Jahren in Deutschland sein Abitur nachholen. Wo kann er das tun? An ...',
      answer_a: 'einer Hochschule.',
      answer_b: 'einem Abendgymnasium.',
      answer_c: 'einer Hauptschule.',
      answer_d: 'einer Privatuniversität.'
    },
    question_262: {
      question: 'Was bedeutet in Deutschland der Grundsatz der Gleichbehandlung?',
      answer_a: 'Niemand darf z.B. wegen einer Behinderung benachteiligt werden.',
      answer_b: 'Man darf andere Personen benachteiligen, wenn ausreichende persönliche Gründe hierfür vorliegen.',
      answer_c: 'Niemand darf gegen Personen klagen, wenn sie benachteiligt wurden.',
      answer_d: 'Es ist für alle Gesetz, benachteiligten Gruppen jährlich Geld zu spenden.'
    },
    question_263: {
      question:
        'In Deutschland sind Jugendliche ab 14 Jahren strafmündig. Das bedeutet: Jugendliche, die 14 Jahre und älter sind und gegen Strafgesetze verstoßen, ...',
      answer_a: 'werden bestraft.',
      answer_b: 'werden wie Erwachsene behandelt.',
      answer_c: 'teilen die Strafe mit ihren Eltern.',
      answer_d: 'werden nicht bestraft.'
    },
    question_264: {
      question: 'Zu welchem Fest tragen Menschen in Deutschland bunte Kostüme und Masken?',
      answer_a: 'am Rosenmontag',
      answer_b: 'am Maifeiertag',
      answer_c: 'beim Oktoberfest',
      answer_d: 'an Pfingsten'
    },
    question_265: {
      question: 'Wohin muss man in Deutschland zuerst gehen, wenn man heiraten möchte?',
      answer_a: 'zum Einwohnermeldeamt',
      answer_b: 'zum Ordnungsamt',
      answer_c: 'zur Agentur für Arbeit',
      answer_d: 'zum Standesamt'
    },
    question_266: {
      question: 'Wann beginnt die gesetzliche Nachtruhe in Deutschland?',
      answer_a: 'wenn die Sonne untergeht',
      answer_b: 'wenn die Nachbarn schlafen gehen',
      answer_c: 'um 0 Uhr, Mitternacht',
      answer_d: 'um 22 Uhr'
    },
    question_267: {
      question:
        'Eine junge Frau in Deutschland, 22 Jahre alt, lebt mit ihrem Freund zusammen. Die Eltern der Frau finden das nicht gut, weil ihnen der Freund nicht gefällt. Was können die Eltern tun?',
      answer_a: 'Sie müssen die Entscheidung der volljährigen Tochter respektieren.',
      answer_b: 'Sie haben das Recht, die Tochter in die elterliche Wohnung zurückzuholen.',
      answer_c: 'Sie können zur Polizei gehen und die Tochter anzeigen.',
      answer_d: 'Sie suchen einen anderen Mann für die Tochter.'
    },
    question_268: {
      question:
        'Eine junge Frau will den Führerschein machen. Sie hat Angst vor der Prüfung, weil ihre Muttersprache nicht Deutsch ist. Was ist richtig?',
      answer_a: 'Sie muss mindestens zehn Jahre in Deutschland leben, bevor sie den Führerschein machen kann.',
      answer_b: 'Wenn sie kein Deutsch kann, darf sie keinen Führerschein haben.',
      answer_c: 'Sie muss den Führerschein in dem Land machen, in dem man ihre Sprache spricht.',
      answer_d:
        'Sie kann die Theorie-Prüfung vielleicht in ihrer Muttersprache machen. Es gibt mehr als zehn Sprachen zur Auswahl.'
    },
    question_269: {
      question:
        'In Deutschland haben Kinder ab dem Alter von drei Jahren bis zur Ersteinschulung einen Anspruch auf ...',
      answer_a: 'monatliches Taschengeld.',
      answer_b: 'einen Platz in einem Sportverein.',
      answer_c: 'einen Kindergartenplatz.',
      answer_d: 'einen Ferienpass.'
    },
    question_270: {
      question: 'Die Volkshochschule in Deutschland ist eine Einrichtung ...',
      answer_a: 'für den Religionsunterricht.',
      answer_b: 'nur für Jugendliche.',
      answer_c: 'zur Weiterbildung.',
      answer_d: 'nur für Rentnerinnen und Rentner.'
    },
    question_271: {
      question: 'Was ist in Deutschland ein Brauch zu Weihnachten?',
      answer_a: 'bunte Eier verstecken',
      answer_b: 'einen Tannenbaum schmücken',
      answer_c: 'sich mit Masken und Kostümen verkleiden',
      answer_d: 'Kürbisse vor die Tür stellen'
    },
    question_272: {
      question: 'Welche Lebensform ist in Deutschland nicht erlaubt?',
      answer_a: 'Mann und Frau sind geschieden und leben mit neuen Partnern zusammen.',
      answer_b: 'Zwei Frauen leben zusammen.',
      answer_c: 'Ein alleinerziehender Vater lebt mit seinen zwei Kindern zusammen.',
      answer_d: 'Ein Mann ist mit zwei Frauen zur selben Zeit verheiratet.'
    },
    question_273: {
      question: 'Bei Erziehungsproblemen gehen Sie in Deutschland ...',
      answer_a: 'zur Ärztin/zum Arzt.',
      answer_b: 'zum Gesundheitsamt.',
      answer_c: 'zum Einwohnermeldeamt.',
      answer_d: 'zum Jugendamt.'
    },
    question_274: {
      question:
        'Sie haben in Deutschland absichtlich einen Brief geöffnet, der an eine andere Person adressiert ist. Was haben Sie nicht beachtet?',
      answer_a: 'das Schweigerecht',
      answer_b: 'das Briefgeheimnis',
      answer_c: 'die Schweigepflicht',
      answer_d: 'die Meinungsfreiheit'
    },
    question_275: {
      question: 'Was braucht man in Deutschland für eine Ehescheidung?',
      answer_a: 'die Einwilligung der Eltern',
      answer_b: 'ein Attest einer Ärztin/eines Arztes',
      answer_c: 'die Einwilligung der Kinder',
      answer_d: 'die Unterstützung einer Anwältin/eines Anwalts'
    },
    question_276: {
      question:
        'Was sollten Sie tun, wenn Sie von Ihrer Ansprechpartnerin/Ihrem Ansprechpartner in einer deutschen Behörde schlecht behandelt werden?',
      answer_a: 'Ich kann nichts tun.',
      answer_b: 'Ich muss mir diese Behandlung gefallen lassen.',
      answer_c: 'Ich drohe der Person.',
      answer_d: 'Ich kann mich bei der Behördenleiterin/beim Behördenleiter beschweren.'
    },
    question_277: {
      question:
        'Eine Frau, die ein zweijähriges Kind hat, bewirbt sich in Deutschland um eine Stelle. Was ist ein Beispiel für Diskriminierung? Sie bekommt die Stelle nur deshalb nicht, weil sie ...',
      answer_a: 'kein Englisch spricht.',
      answer_b: 'zu hohe Gehaltsvorstellungen hat.',
      answer_c: 'keine Erfahrungen in diesem Beruf hat.',
      answer_d: 'Mutter ist.'
    },
    question_278: {
      question:
        'Ein Mann im Rollstuhl hat sich auf eine Stelle als Buchhalter beworben. Was ist ein Beispiel für Diskriminierung? Er bekommt die Stelle nur deshalb nicht, weil er ...',
      answer_a: 'im Rollstuhl sitzt.',
      answer_b: 'keine Erfahrung hat.',
      answer_c: 'zu hohe Gehaltsvorstellungen hat.',
      answer_d: 'kein Englisch spricht.'
    },
    question_279: {
      question:
        'In den meisten Mietshäusern in Deutschland gibt es eine "Hausordnung". Was steht in einer solchen "Hausordnung"? Sie nennt ...',
      answer_a: 'Regeln für die Benutzung öffentlicher Verkehrsmittel.',
      answer_b: 'alle Mieterinnen und Mieter im Haus.',
      answer_c: 'Regeln, an die sich alle Bewohnerinnen und Bewohner halten müssen.',
      answer_d: 'die Adresse des nächsten Ordnungsamtes.'
    },
    question_280: {
      question: 'Wenn Sie sich in Deutschland gegen einen falschen Steuerbescheid wehren wollen, müssen Sie ...',
      answer_a: 'nichts machen.',
      answer_b: 'den Bescheid wegwerfen.',
      answer_c: 'Einspruch einlegen.',
      answer_d: 'warten, bis ein anderer Bescheid kommt.'
    },
    question_281: {
      question:
        'Zwei Freunde wollen in ein öffentliches Schwimmbad in Deutschland. Beide haben eine dunkle Hautfarbe und werden deshalb nicht hineingelassen. Welches Recht wird in dieser Situation verletzt? Das Recht auf ...',
      answer_a: 'Meinungsfreiheit',
      answer_b: 'Gleichbehandlung',
      answer_c: 'Versammlungsfreiheit',
      answer_d: 'Freizügigkeit'
    },
    question_282: {
      question:
        'Welches Ehrenamt müssen deutsche Staatsbürgerinnen und Staatsbürger übernehmen, wenn sie dazu aufgefordert werden?',
      answer_a: 'Vereinstrainerin/Vereinstrainer',
      answer_b: 'Wahlhelferin/Wahlhelfer',
      answer_c: 'Bibliotheksaufsicht',
      answer_d: 'Lehrerin/Lehrer'
    },
    question_283: {
      question: 'Was tun Sie, wenn Sie eine falsche Rechnung von einer deutschen Behörde bekommen?',
      answer_a: 'Ich lasse die Rechnung liegen.',
      answer_b: 'Ich lege Widerspruch bei der Behörde ein.',
      answer_c: 'Ich schicke die Rechnung an die Behörde zurück.',
      answer_d: 'Ich gehe mit der Rechnung zum Finanzamt.'
    },
    question_284: {
      question: 'Was man für die Arbeit können muss, ändert sich in Zukunft sehr schnell. Was kann man tun?',
      answer_a: 'Es ist egal, was man lernt.',
      answer_b: 'Erwachsene müssen auch nach der Ausbildung immer weiter lernen.',
      answer_c:
        'Kinder lernen in der Schule alles, was im Beruf wichtig ist. Nach der Schule muss man nicht weiter lernen.',
      answer_d: 'Alle müssen früher aufhören zu arbeiten, weil sich alles ändert.'
    },
    question_285: {
      question:
        'Frau Frost arbeitet als fest angestellte Mitarbeiterin in einem Büro. Was muss sie nicht von ihrem Gehalt bezahlen?',
      answer_a: 'Lohnsteuer',
      answer_b: 'Beiträge zur Arbeitslosenversicherung',
      answer_c: 'Beiträge zur Renten- und Krankenversicherung',
      answer_d: 'Umsatzsteuer'
    },
    question_286: {
      question:
        'Welche Organisation in einer Firma hilft den Arbeitnehmerinnen und Arbeitnehmern bei Problemen mit der Arbeitgeberin/dem Arbeitgeber?',
      answer_a: 'der Betriebsrat',
      answer_b: 'die Betriebsprüferin/der Betriebsprüfer',
      answer_c: 'die Betriebsgruppe',
      answer_d: 'das Betriebsmanagement'
    },
    question_287: {
      question: 'Sie möchten bei einer Firma in Deutschland ihr Arbeitsverhältnis beenden. Was müssen Sie beachten?',
      answer_a: 'die Gehaltszahlungen',
      answer_b: 'die Arbeitszeit',
      answer_c: 'die Kündigungsfrist',
      answer_d: 'die Versicherungspflicht'
    },
    question_288: {
      question: 'Woraus begründet sich Deutschlands besondere Verantwortung für Israel?',
      answer_a: 'aus der Mitgliedschaft in der Europäischen Union (EU)',
      answer_b: 'aus den nationalsozialistischen Verbrechen gegen Juden',
      answer_c: 'aus dem Grundgesetz der Bundesrepublik Deutschland',
      answer_d: 'aus der christlichen Tradition'
    },
    question_289: {
      question:
        'Ein Mann mit dunkler Hautfarbe bewirbt sich um eine Stelle als Kellner in einem Restaurant in Deutschland. Was ist ein Beispiel für Diskriminierung? Er bekommt die Stelle nur deshalb nicht, weil ...',
      answer_a: 'seine Deutschkenntnisse zu gering sind.',
      answer_b: 'er zu hohe Gehaltsvorstellungen hat.',
      answer_c: 'er eine dunkle Haut hat.',
      answer_d: 'er keine Erfahrungen im Beruf hat.'
    },
    question_290: {
      question:
        'Sie haben in Deutschland einen Fernseher gekauft. Zu Hause packen Sie den Fernseher aus, doch er funktioniert nicht. Der Fernseher ist kaputt. Was können Sie machen?',
      answer_a: 'eine Anzeige schreiben',
      answer_b: 'den Fernseher reklamieren',
      answer_c: 'das Gerät ungefragt austauschen',
      answer_d: 'die Garantie verlängern'
    },
    question_291: {
      question:
        'Warum muss man in Deutschland bei der Steuererklärung aufschreiben, ob man zu einer Kirche gehört oder nicht? Weil ...',
      answer_a: 'es eine Kirchensteuer gibt, die an die Einkommen- und Lohnsteuer geknüpft ist.',
      answer_b: 'das für die Statistik in Deutschland wichtig ist.',
      answer_c: 'man mehr Steuern zahlen muss, wenn man nicht zu einer Kirche gehört.',
      answer_d: 'die Kirche für die Steuererklärung verantwortlich ist.'
    },
    question_292: {
      question: 'Die Menschen in Deutschland leben nach dem Grundsatz der religiösen Toleranz. Was bedeutet das?',
      answer_a: 'Es dürfen keine Moscheen gebaut werden.',
      answer_b: 'Alle Menschen glauben an Gott.',
      answer_c: 'Jeder kann glauben, was er möchte.',
      answer_d: 'Der Staat entscheidet, an welchen Gott die Menschen glauben.'
    },
    question_293: {
      question: 'Was ist in Deutschland ein Brauch zu Ostern?',
      answer_a: 'Kürbisse vor die Tür stellen',
      answer_b: 'einen Tannenbaum schmücken',
      answer_c: 'Eier bemalen',
      answer_d: 'Raketen in die Luft schießen'
    },
    question_294: {
      question: 'Pfingsten ist ein ...',
      answer_a: 'christlicher Feiertag.',
      answer_b: 'deutscher Gedenktag.',
      answer_c: 'internationaler Trauertag.',
      answer_d: 'bayerischer Brauch.'
    },
    question_295: {
      question: 'Welche Religion hat die europäische und deutsche Kultur geprägt?',
      answer_a: 'der Hinduismus',
      answer_b: 'das Christentum',
      answer_c: 'der Buddhismus',
      answer_d: 'der Islam'
    },
    question_296: {
      question: 'In Deutschland nennt man die letzten vier Wochen vor Weihnachten ...',
      answer_a: 'den Buß- und Bettag.',
      answer_b: 'das Erntedankfest.',
      answer_c: 'die Adventszeit.',
      answer_d: 'Allerheiligen.'
    },
    question_297: {
      question: 'Aus welchem Land sind die meisten Migrantinnen und Migranten nach Deutschland gekommen?',
      answer_a: 'Italien',
      answer_b: 'Polen',
      answer_c: 'Marokko',
      answer_d: 'Türkei'
    },
    question_298: {
      question: 'In der DDR lebten vor allem Migrantinnen und Migranten aus ...',
      answer_a: 'Vietnam, Polen, Mosambik.',
      answer_b: 'Frankreich, Rumänien, Somalia.',
      answer_c: 'Chile, Ungarn, Simbabwe.',
      answer_d: 'Nordkorea, Mexiko, Ägypten.'
    },
    question_299: {
      question:
        'Ausländische Arbeitnehmerinnen und Arbeitnehmer, die in den 50er und 60er Jahren von der Bundesrepublik Deutschland angeworben wurden, nannte man ...',
      answer_a: 'Schwarzarbeiterinnen/Schwarzarbeiter.',
      answer_b: 'Gastarbeiterinnen/Gastarbeiter.',
      answer_c: 'Zeitarbeiterinnen/Zeitarbeiter.',
      answer_d: 'Schichtarbeiterinnen/Schichtarbeiter.'
    },
    question_300: {
      question:
        'Aus welchem Land kamen die ersten Gastarbeiterinnen und Gastarbeiter in die Bundesrepublik Deutschland?',
      answer_a: 'Italien',
      answer_b: 'Spanien',
      answer_c: 'Portugal',
      answer_d: 'Türkei'
    }
  }
}
