// Auto-generated by scripts/merge-translations.mjs from scripts/output/en-batch-*.json.
export default {
  questions: {
    question_1: {
      question: 'In Germany, people are allowed to openly say something against the government because ...',
      answer_a: 'freedom of religion applies here.',
      answer_b: 'people pay taxes.',
      answer_c: 'people have the right to vote.',
      answer_d: 'freedom of expression applies here.'
    },
    question_2: {
      question:
        "In Germany, parents can decide, until their child's 14th birthday, whether the child takes part in ...",
      answer_a: 'history class.',
      answer_b: 'religious education.',
      answer_c: 'politics class.',
      answer_d: 'language class.'
    },
    question_3: {
      question: 'Germany is a state based on the rule of law (Rechtsstaat). What does this mean?',
      answer_a: 'All residents and the state must abide by the law.',
      answer_b: 'The state does not have to abide by the law.',
      answer_c: 'Only Germans have to obey the law.',
      answer_d: 'The courts make the laws.'
    },
    question_4: {
      question: 'Which right is one of the basic rights in Germany?',
      answer_a: 'The right to own weapons',
      answer_b: 'The law of the fist (might makes right)',
      answer_c: 'Freedom of expression',
      answer_d: 'Vigilante justice'
    },
    question_5: {
      question: 'Elections in Germany are free. What does that mean?',
      answer_a: 'You are allowed to accept money if you vote for a particular candidate in return.',
      answer_b: 'Only people who have never been in prison are allowed to vote.',
      answer_c:
        'Voters may not be influenced or forced to vote a certain way, and must not suffer any disadvantages because of how they vote.',
      answer_d: 'All eligible voters must vote.'
    },
    question_6: {
      question: 'What is the German constitution called?',
      answer_a: "People's Law",
      answer_b: 'Federal Law',
      answer_c: 'German Law',
      answer_d: 'Basic Law'
    },
    question_7: {
      question: 'Which right is one of the basic rights guaranteed by the German constitution? The right to ...',
      answer_a: 'freedom of belief and conscience',
      answer_b: 'entertainment',
      answer_c: 'employment',
      answer_d: 'housing'
    },
    question_8: {
      question: "What is not stated in Germany's Basic Law?",
      answer_a: 'Human dignity is inviolable.',
      answer_b: 'Everyone should have the same amount of money.',
      answer_c: 'Everyone may express their opinion.',
      answer_d: 'Everyone is equal before the law.'
    },
    question_9: {
      question: 'Which basic right in Germany applies only to foreign nationals? The basic right to ...',
      answer_a: 'protection of the family',
      answer_b: 'human dignity',
      answer_c: 'asylum',
      answer_d: 'freedom of expression'
    },
    question_10: {
      question: "Which of the following is compatible with Germany's Basic Law?",
      answer_a: 'corporal punishment',
      answer_b: 'torture',
      answer_c: 'the death penalty',
      answer_d: 'a fine'
    },
    question_11: {
      question: 'What is the constitution of the Federal Republic of Germany called?',
      answer_a: 'Basic Law',
      answer_b: 'Federal Constitution',
      answer_c: 'Legal Code',
      answer_d: 'Constitutional Treaty'
    },
    question_12: {
      question: 'A party in the German Bundestag wants to abolish freedom of the press. Is that possible?',
      answer_a: 'Yes, if more than half of the members of the Bundestag vote in favor.',
      answer_b: 'Yes, but two-thirds of the members of the Bundestag must vote in favor.',
      answer_c: 'No, because freedom of the press is a basic right. It cannot be abolished.',
      answer_d: 'No, because only the Bundesrat can abolish freedom of the press.'
    },
    question_13: {
      question: 'In parliament, the term "opposition" refers to ...',
      answer_a: 'the governing parties.',
      answer_b: 'the parliamentary group with the most members.',
      answer_c: 'all parties that cleared the 5% threshold in the last election.',
      answer_d: 'all members of parliament who do not belong to the governing party/parties.'
    },
    question_14: {
      question: 'Freedom of expression in Germany means that I ...',
      answer_a: 'am allowed to insult passersby on the street.',
      answer_b: 'can express my opinion on the internet.',
      answer_c: 'am allowed to publicly display Nazi, Hamas, or Islamic State symbols.',
      answer_d: 'may only express my opinion as long as I do not contradict the government.'
    },
    question_15: {
      question: "What does Germany's Basic Law prohibit?",
      answer_a: 'military service',
      answer_b: 'forced labor',
      answer_c: 'free choice of occupation',
      answer_d: 'working abroad'
    },
    question_16: {
      question: 'When is freedom of expression restricted in Germany?',
      answer_a: 'when publicly spreading false claims about individuals',
      answer_b: 'when expressing opinions about the Federal Government',
      answer_c: 'when discussing religions',
      answer_d: 'when criticizing the state'
    },
    question_17: {
      question: 'German law prohibits ...',
      answer_a: 'freedom of expression for residents.',
      answer_b: 'petitions by citizens.',
      answer_c: 'freedom of assembly for residents.',
      answer_d: 'unequal treatment of citizens by the state.'
    },
    question_18: {
      question: 'Which basic right is guaranteed in Article 1 of the Basic Law of the Federal Republic of Germany?',
      answer_a: 'the inviolability of human dignity',
      answer_b: 'the right to life',
      answer_c: 'freedom of religion',
      answer_d: 'freedom of expression'
    },
    question_19: {
      question: 'What is meant by the right to "freedom of movement" in Germany?',
      answer_a: 'You may choose your own place of residence.',
      answer_b: 'You can change your occupation.',
      answer_c: 'You may choose a different religion.',
      answer_d: 'You may only appear in public lightly dressed.'
    },
    question_20: {
      question: 'A party in Germany pursues the goal of establishing a dictatorship. It is then ...',
      answer_a: 'tolerant.',
      answer_b: 'oriented toward the rule of law.',
      answer_c: 'law-abiding.',
      answer_d: 'unconstitutional.'
    },
    question_21: {
      question: 'Which is the coat of arms of the Federal Republic of Germany?',
      answer_a: 'Image 1',
      answer_b: 'Image 2',
      answer_c: 'Image 3',
      answer_d: 'Image 4'
    },
    question_22: {
      question: 'What form of government does Germany have?',
      answer_a: 'Monarchy',
      answer_b: 'Dictatorship',
      answer_c: 'Republic',
      answer_d: 'Principality'
    },
    question_23: {
      question: 'In Germany, most working people are ...',
      answer_a: 'employed in small family businesses.',
      answer_b: 'working on a voluntary basis for a federal state.',
      answer_c: 'self-employed with their own company.',
      answer_d: 'employed by a company or a government agency.'
    },
    question_24: {
      question: 'How many federal states does the Federal Republic of Germany have?',
      answer_a: '14',
      answer_b: '15',
      answer_c: '16',
      answer_d: '17'
    },
    question_25: {
      question: 'Which of the following is not a federal state of the Federal Republic of Germany?',
      answer_a: 'Alsace-Lorraine',
      answer_b: 'North Rhine-Westphalia',
      answer_c: 'Mecklenburg-Western Pomerania',
      answer_d: 'Saxony-Anhalt'
    },
    question_26: {
      question: 'Germany is ...',
      answer_a: 'a communist republic.',
      answer_b: 'a democratic and social federal state.',
      answer_c: 'a capitalist and social monarchy.',
      answer_d: 'a social and socialist federal state.'
    },
    question_27: {
      question: 'Germany is ...',
      answer_a: 'a socialist state.',
      answer_b: 'a federal state.',
      answer_c: 'a dictatorship.',
      answer_d: 'a monarchy.'
    },
    question_28: {
      question: 'Who elects the members of the Bundestag in Germany?',
      answer_a: 'the military',
      answer_b: 'the business community',
      answer_c: 'the eligible voters',
      answer_d: 'the administration'
    },
    question_29: {
      question: 'Which animal is the heraldic animal of the Federal Republic of Germany?',
      answer_a: 'Lion',
      answer_b: 'Eagle',
      answer_c: 'Bear',
      answer_d: 'Horse'
    },
    question_30: {
      question: 'What is not a feature of our democracy?',
      answer_a: 'regular elections',
      answer_b: 'press censorship',
      answer_c: 'freedom of expression',
      answer_d: 'different parties'
    },
    question_31: {
      question: 'In Germany, the cooperation of parties to form a government is called a ...',
      answer_a: 'unity.',
      answer_b: 'coalition.',
      answer_c: 'ministry.',
      answer_d: 'parliamentary group.'
    },
    question_32: {
      question: 'Which of the following is not a branch of state power in Germany?',
      answer_a: 'Legislature',
      answer_b: 'Government',
      answer_c: 'Press',
      answer_d: 'Judiciary'
    },
    question_33: {
      question: 'Which statement is correct? In Germany ...',
      answer_a: 'the state and religious communities are separate from one another.',
      answer_b: 'religious communities form the state.',
      answer_c: 'the state is dependent on religious communities.',
      answer_d: 'the state and religious communities form a single unit.'
    },
    question_34: {
      question: 'What is Germany not?',
      answer_a: 'a democracy',
      answer_b: 'a state based on the rule of law',
      answer_c: 'a monarchy',
      answer_d: 'a welfare state'
    },
    question_35: {
      question: 'How does the German state finance social insurance?',
      answer_a: 'Church tax',
      answer_b: 'Social security contributions',
      answer_c: 'Donations',
      answer_d: 'Club membership fees'
    },
    question_36: {
      question: 'Which measure provides social security in Germany?',
      answer_a: 'health insurance',
      answer_b: 'car insurance',
      answer_c: 'building insurance',
      answer_d: 'liability insurance'
    },
    question_37: {
      question: 'What are the heads of government of most German federal states called?',
      answer_a: 'First Minister',
      answer_b: 'Prime Minister',
      answer_c: 'Senator',
      answer_d: 'Minister-President'
    },
    question_38: {
      question: 'The Federal Republic of Germany is a democratic and social ...',
      answer_a: 'confederation of states.',
      answer_b: 'federal state.',
      answer_c: 'confederation.',
      answer_d: 'centralized state.'
    },
    question_39: {
      question: 'What does every German federal state have?',
      answer_a: 'its own foreign minister',
      answer_b: 'its own currency',
      answer_c: 'its own army',
      answer_d: 'its own government'
    },
    question_40: {
      question: 'What are the opening words of the German national anthem?',
      answer_a: 'Völker, hört die Signale ... (Peoples, hear the signals ...)',
      answer_b: 'Einigkeit und Recht und Freiheit ... (Unity and justice and freedom ...)',
      answer_c: 'Freude schöner Götterfunken ... (Joy, beautiful spark of the divine ...)',
      answer_d: 'Deutschland einig Vaterland ... (Germany, united fatherland ...)'
    },
    question_41: {
      question: 'Why are there more than one party in a democracy?',
      answer_a: 'because this allows the different opinions of citizens to be represented',
      answer_b: 'so that bribery in politics is limited',
      answer_c: 'to prevent political demonstrations',
      answer_d: 'to stimulate economic competition'
    },
    question_42: {
      question: 'Who passes a new law in Germany?',
      answer_a: 'the government',
      answer_b: 'the parliament',
      answer_c: 'the courts',
      answer_d: 'the police'
    },
    question_43: {
      question: 'When can a party be banned in Germany?',
      answer_a: 'if its election campaign is too expensive',
      answer_b: 'if it fights against the constitution',
      answer_c: 'if it criticizes the head of state',
      answer_d: 'if its platform proposes a new direction'
    },
    question_44: {
      question: 'As a citizen in Germany, who can you not vote for directly?',
      answer_a: 'Members of the European Parliament',
      answer_b: 'The Federal President',
      answer_c: 'Members of a state parliament (Landtag)',
      answer_d: 'Members of the Bundestag'
    },
    question_45: {
      question: 'Which type of insurance does long-term care insurance belong to?',
      answer_a: 'Social insurance',
      answer_b: 'Accident insurance',
      answer_c: 'Home contents insurance',
      answer_d: 'Liability and fire insurance'
    },
    question_46: {
      question: 'The German state has many responsibilities. Which of the following is one of them?',
      answer_a: 'It builds roads and schools.',
      answer_b: 'It sells food and clothing.',
      answer_c: 'It provides all residents with free newspapers.',
      answer_d: 'It manufactures cars and buses.'
    },
    question_47: {
      question: 'The German state has many responsibilities. Which of the following is not one of them?',
      answer_a: 'It pays for vacation trips for all citizens.',
      answer_b: 'It pays child benefit.',
      answer_c: 'It supports museums.',
      answer_d: 'It supports athletes.'
    },
    question_48: {
      question: "Which body is not one of Germany's constitutional bodies?",
      answer_a: 'the Bundesrat',
      answer_b: 'the Federal President',
      answer_c: "the citizens' assembly",
      answer_d: 'the government'
    },
    question_49: {
      question: 'Who determines school policy in Germany?',
      answer_a: 'teachers',
      answer_b: 'the federal states',
      answer_c: 'the Ministry of Family Affairs',
      answer_d: 'the universities'
    },
    question_50: {
      question: 'The economic system in Germany is called a ...',
      answer_a: 'free centrally planned economy.',
      answer_b: 'social market economy.',
      answer_c: 'directed centrally planned economy.',
      answer_d: 'planned economy.'
    },
    question_51: {
      question: 'It is not part of a democratic constitutional state that ...',
      answer_a: 'people can express criticism of the government.',
      answer_b: 'citizens are allowed to demonstrate peacefully.',
      answer_c: 'people are arrested without reason by a private police force.',
      answer_d: 'someone commits a crime and is therefore arrested.'
    },
    question_52: {
      question: 'What does "popular sovereignty" mean? All state authority derives from the ...',
      answer_a: 'people.',
      answer_b: 'Bundestag.',
      answer_c: 'Prussian king.',
      answer_d: 'Federal Constitutional Court.'
    },
    question_53: {
      question: 'What does "Rechtsstaat" (constitutional state) mean in Germany?',
      answer_a: 'The state is always right.',
      answer_b: 'There are only right-wing parties.',
      answer_c: 'Citizens decide on the laws.',
      answer_d: 'The state must abide by the laws.'
    },
    question_54: {
      question: 'Which of the following is not a branch of state power in Germany?',
      answer_a: 'Legislature',
      answer_b: 'Judiciary',
      answer_c: 'Executive',
      answer_d: 'Directive'
    },
    question_55: {
      question: 'What does this picture show?',
      answer_a: 'the seat of the Bundestag in Berlin',
      answer_b: 'the Federal Constitutional Court in Karlsruhe',
      answer_c: 'the Bundesrat building in Berlin',
      answer_d: 'the Federal Chancellery in Berlin'
    },
    question_56: {
      question: 'Which office in Germany belongs to the municipal administration?',
      answer_a: 'parish office',
      answer_b: 'public order office',
      answer_c: 'tax office',
      answer_d: 'Federal Foreign Office'
    },
    question_57: {
      question: 'Who is usually elected President of the German Bundestag?',
      answer_a: 'the oldest member of parliament',
      answer_b: 'the Minister-President of the largest federal state',
      answer_c: 'a former Federal Chancellor',
      answer_d: 'a member of parliament from the strongest parliamentary group'
    },
    question_58: {
      question: 'Who appoints the ministers of the Federal Government in Germany?',
      answer_a: 'the President of the Federal Constitutional Court',
      answer_b: 'the Federal President',
      answer_c: 'the President of the Bundesrat',
      answer_d: 'the President of the Bundestag'
    },
    question_59: {
      question: 'How many years ago did the first Jewish community exist in the territory of present-day Germany?',
      answer_a: 'about 300 years ago',
      answer_b: 'about 700 years ago',
      answer_c: 'about 1150 years ago',
      answer_d: 'about 1700 years ago'
    },
    question_60: {
      question: 'In Germany, the Bundestag and the Bundesrat belong to the ...',
      answer_a: 'executive.',
      answer_b: 'legislature.',
      answer_c: 'directive.',
      answer_d: 'judiciary.'
    },
    question_61: {
      question: 'What does "popular sovereignty" mean?',
      answer_a: 'The king/queen rules over the people.',
      answer_b: 'The Federal Constitutional Court stands above the constitution.',
      answer_c: 'Interest groups exercise sovereignty together with the government.',
      answer_d: 'State authority derives from the people.'
    },
    question_62: {
      question: 'When the parliament of a German federal state is elected, this is called a ...',
      answer_a: 'municipal election',
      answer_b: 'state parliament election',
      answer_c: 'European election',
      answer_d: 'Bundestag election'
    },
    question_63: {
      question: 'Which of the following is not part of the executive in Germany?',
      answer_a: 'the police',
      answer_b: 'the courts',
      answer_c: 'the tax office',
      answer_d: 'the ministries'
    },
    question_64: {
      question: 'Today the Federal Republic of Germany is organized into ...',
      answer_a: 'four occupation zones.',
      answer_b: 'an eastern state and a western state.',
      answer_c: '16 cantons.',
      answer_d: 'the federal government, the states, and the municipalities.'
    },
    question_65: {
      question: 'It is not one of the tasks of the German Bundestag to ...',
      answer_a: 'draft laws.',
      answer_b: 'oversee the Federal Government.',
      answer_c: 'elect the Federal Chancellor.',
      answer_d: 'form the federal cabinet.'
    },
    question_66: {
      question: 'Which cities have the largest Jewish communities in Germany?',
      answer_a: 'Berlin and Munich',
      answer_b: 'Hamburg and Essen',
      answer_c: 'Nuremberg and Stuttgart',
      answer_d: 'Worms and Speyer'
    },
    question_67: {
      question: 'What is primarily a task of the federal states in Germany?',
      answer_a: 'defense policy',
      answer_b: 'foreign policy',
      answer_c: 'economic policy',
      answer_d: 'education policy'
    },
    question_68: {
      question: 'Why does the state control the school system in Germany?',
      answer_a: 'because there are only state (public) schools in Germany',
      answer_b: 'because all pupils must obtain a school-leaving qualification',
      answer_c: 'because there are different types of schools in the federal states',
      answer_d: "because it is the state's task under the Basic Law"
    },
    question_69: {
      question:
        'The Federal Republic of Germany has a three-tier administrative structure. What is the lowest political tier called?',
      answer_a: 'city councils',
      answer_b: 'district administrators',
      answer_c: 'municipalities',
      answer_d: 'district offices'
    },
    question_70: {
      question:
        'In 1974, German Federal President Gustav Heinemann hands Helmut Schmidt the certificate of appointment as Federal Chancellor. What is one of the tasks of the German Federal President?',
      answer_a: 'He/she runs the day-to-day business of government.',
      answer_b: 'He/she oversees the governing party.',
      answer_c: 'He/she selects the ministers.',
      answer_d: 'He/she proposes a candidate for Chancellor for election.'
    },
    question_71: {
      question: 'Where does the German Federal Chancellor most often stay? Most often, he/she is ...',
      answer_a: 'in Bonn, because the Federal Chancellery and the Bundestag are located there.',
      answer_b: "at Schloss Meseberg, the Federal Government's guest house, to receive state guests.",
      answer_c: 'at Schloss Bellevue, the official residence of the Federal President, to receive state guests.',
      answer_d: 'in Berlin, because the Federal Chancellery and the Bundestag are located there.'
    },
    question_72: {
      question: 'What is the name of the current Federal Chancellor of Germany?',
      answer_a: 'Gerhard Schröder',
      answer_b: 'Angela Merkel',
      answer_c: 'Ursula von der Leyen',
      answer_d: 'Friedrich Merz'
    },
    question_73: {
      question: 'The two largest parliamentary groups in the German Bundestag are currently called ...',
      answer_a: 'CDU/CSU and AfD.',
      answer_b: 'Die Linke and Bündnis 90/Die Grünen.',
      answer_c: 'Bündnis 90/Die Grünen and SPD.',
      answer_d: 'Die Linke and CDU/CSU.'
    },
    question_74: {
      question: 'What is the parliament for all of Germany called?',
      answer_a: 'Federal Convention',
      answer_b: "People's Chamber",
      answer_c: 'Bundestag',
      answer_d: 'Federal Court of Justice'
    },
    question_75: {
      question: "What is the name of Germany's current head of state?",
      answer_a: 'Frank-Walter Steinmeier',
      answer_b: 'Bärbel Bas',
      answer_c: 'Bodo Ramelow',
      answer_d: 'Joachim Gauck'
    },
    question_76: {
      question: 'What does the abbreviation CDU stand for in Germany?',
      answer_a: 'Christian German Union',
      answer_b: 'Club of German Entrepreneurs',
      answer_c: 'Christian German Environmental Protection',
      answer_d: 'Christian Democratic Union'
    },
    question_77: {
      question: 'What is the Bundeswehr?',
      answer_a: 'the German police',
      answer_b: 'a German port',
      answer_c: "a German citizens' initiative",
      answer_d: 'the German armed forces'
    },
    question_78: {
      question: 'What does the abbreviation SPD stand for?',
      answer_a: 'Socialist Party of Germany',
      answer_b: 'Social Policy Party of Germany',
      answer_c: 'Social Democratic Party of Germany',
      answer_d: 'Socially Just Party of Germany'
    },
    question_79: {
      question: 'What does the abbreviation FDP stand for in Germany?',
      answer_a: 'Peaceful Demonstrative Party',
      answer_b: 'Free Germany Party',
      answer_c: 'Leading Democratic Party',
      answer_d: 'Free Democratic Party'
    },
    question_80: {
      question: 'Which court in Germany is responsible for interpreting the Basic Law?',
      answer_a: 'Higher Regional Court',
      answer_b: 'Local Court',
      answer_c: 'Federal Constitutional Court',
      answer_d: 'Administrative Court'
    },
    question_81: {
      question: 'Who elects the Federal Chancellor in Germany?',
      answer_a: 'the Bundesrat',
      answer_b: 'the Federal Convention',
      answer_c: 'the people',
      answer_d: 'the Bundestag'
    },
    question_82: {
      question: 'Who leads the German federal cabinet?',
      answer_a: 'the President of the Bundestag',
      answer_b: 'the Federal President',
      answer_c: 'the President of the Bundesrat',
      answer_d: 'the Federal Chancellor'
    },
    question_83: {
      question: 'Who elects the German Federal Chancellor?',
      answer_a: 'the people',
      answer_b: 'the Federal Convention',
      answer_c: 'the Bundestag',
      answer_d: 'the Federal Government'
    },
    question_84: {
      question: 'What is the main task of the German Federal President? He/she ...',
      answer_a: 'governs the country.',
      answer_b: 'drafts the laws.',
      answer_c: 'represents the country.',
      answer_d: 'monitors compliance with the laws.'
    },
    question_85: {
      question: 'Who makes up the German Bundesrat?',
      answer_a: 'the members of the Bundestag',
      answer_b: 'the ministers of the Federal Government',
      answer_c: 'the representatives of the state governments',
      answer_d: 'party members'
    },
    question_86: {
      question: 'Who elects the Federal President in Germany?',
      answer_a: 'the Federal Convention',
      answer_b: 'the Bundesrat',
      answer_c: 'the federal parliament',
      answer_d: 'the Federal Constitutional Court'
    },
    question_87: {
      question: 'Who is the head of state of the Federal Republic of Germany?',
      answer_a: 'the Federal Chancellor',
      answer_b: 'the Federal President',
      answer_c: 'the President of the Bundesrat',
      answer_d: 'the President of the Bundestag'
    },
    question_88: {
      question: 'The parliamentary opposition in the German Bundestag ...',
      answer_a: 'oversees the government.',
      answer_b: 'decides who becomes a federal minister.',
      answer_c: 'determines who sits in the Bundesrat.',
      answer_d: 'proposes the heads of government of the states.'
    },
    question_89: {
      question: 'What is the association of members of parliament from one party called in Germany?',
      answer_a: 'association',
      answer_b: 'council of elders',
      answer_c: 'parliamentary group',
      answer_d: 'opposition'
    },
    question_90: {
      question: 'The German federal states participate in federal legislation through ...',
      answer_a: 'the Bundesrat.',
      answer_b: 'the Federal Convention.',
      answer_c: 'the Bundestag.',
      answer_d: 'the Federal Government.'
    },
    question_91: {
      question:
        'In Germany, a change of government in a federal state can have an impact on federal politics. Governing becomes ...',
      answer_a: 'more difficult if this changes the majority in the Bundestag.',
      answer_b: 'easier if new parties enter the Bundesrat as a result.',
      answer_c: 'more difficult if this changes the majority in the Bundesrat.',
      answer_d: 'easier if it is a wealthy federal state.'
    },
    question_92: {
      question: 'What does the abbreviation CSU stand for in Germany?',
      answer_a: 'Christian Secure Union',
      answer_b: 'Christian South German Union',
      answer_c: 'Christian Social Business Association',
      answer_d: 'Christian Social Union'
    },
    question_93: {
      question: 'The more "second votes" a party receives in a Bundestag election, the ...',
      answer_a: 'fewer first votes it can have.',
      answer_b: "more of the party's direct candidates enter parliament.",
      answer_c: 'greater the risk of having to form a coalition.',
      answer_d: 'more seats the party receives in parliament.'
    },
    question_94: {
      question: 'From what age is one allowed to vote in the election to the German Bundestag?',
      answer_a: '16',
      answer_b: '18',
      answer_c: '21',
      answer_d: '23'
    },
    question_95: {
      question: 'What applies to most children in Germany?',
      answer_a: 'compulsory voting',
      answer_b: 'compulsory school attendance',
      answer_c: 'duty of confidentiality',
      answer_d: 'compulsory religious instruction'
    },
    question_96: {
      question: 'How can someone who denies the Holocaust be punished?',
      answer_a: 'reduction of social benefits',
      answer_b: 'up to 100 hours of community service',
      answer_c: 'not at all, Holocaust denial is permitted',
      answer_d: 'with imprisonment of up to five years or a fine'
    },
    question_97: {
      question: 'What does one automatically pay in Germany when permanently employed?',
      answer_a: 'social insurance contributions',
      answer_b: 'social assistance',
      answer_c: 'child benefit',
      answer_d: 'housing benefit'
    },
    question_98: {
      question: 'When members of parliament in the German Bundestag switch their parliamentary group, ...',
      answer_a: 'they are no longer allowed to take part in parliamentary sessions.',
      answer_b: 'the government can lose its majority.',
      answer_c: 'the Federal President must first give his/her consent.',
      answer_d: 'the voters of these members of parliament are allowed to vote again.'
    },
    question_99: {
      question: 'Who pays for social insurance in Germany?',
      answer_a: 'employers and employees',
      answer_b: 'only employees',
      answer_c: 'all nationals',
      answer_d: 'only employers'
    },
    question_100: {
      question: 'Which of the following is not part of statutory social insurance?',
      answer_a: 'life insurance',
      answer_b: 'statutory pension insurance',
      answer_c: 'unemployment insurance',
      answer_d: 'long-term care insurance'
    },
    question_101: {
      question: 'Trade unions are interest associations of ...',
      answer_a: 'young people.',
      answer_b: 'employees.',
      answer_c: 'pensioners.',
      answer_d: 'employers.'
    },
    question_102: {
      question:
        'What can someone in the Federal Republic of Germany be honored with if they have made a special contribution in the political, economic, cultural, intellectual, or social field? With the ...',
      answer_a: 'Federal Cross of Merit',
      answer_b: 'Federal Eagle',
      answer_c: 'Patriotic Order of Merit',
      answer_d: 'honorary title "Hero of the German Democratic Republic"'
    },
    question_103: {
      question: 'What is referred to in Germany as a "traffic light coalition"? The cooperation ...',
      answer_a: 'of the Bundestag parliamentary groups of the CDU and CSU',
      answer_b: 'of the SPD, FDP, and Bündnis 90/Die Grünen in a government',
      answer_c: 'of the CSU, Die LINKE, and Bündnis 90/Die Grünen in a government',
      answer_d: 'of the Bundestag parliamentary groups of the CDU and SPD'
    },
    question_104: {
      question: 'A woman in Germany loses her job. What must not be the reason for this dismissal?',
      answer_a: 'The woman has been sick and unable to work for a long time.',
      answer_b: 'The woman often came to work late.',
      answer_c: 'The woman takes care of private matters during working hours.',
      answer_d: 'The woman is having a baby and her boss knows about it.'
    },
    question_105: {
      question: 'What is one task of election helpers in Germany?',
      answer_a: 'They help elderly people cast their vote in the polling booth.',
      answer_b: 'They write the polling notifications before the election.',
      answer_c: 'They pass on interim results to the media.',
      answer_d: 'They count the votes after the election has ended.'
    },
    question_106: {
      question: 'In Germany, volunteer election helpers assist with elections. What is one task of election helpers?',
      answer_a: 'They help children and elderly people with voting.',
      answer_b: 'They write cards and letters stating the polling location.',
      answer_c: 'They pass on interim results to journalists.',
      answer_d: 'They count the votes after the election has ended.'
    },
    question_107: {
      question: 'For how many years is the Bundestag elected in Germany?',
      answer_a: '2 years',
      answer_b: '4 years',
      answer_c: '6 years',
      answer_d: '8 years'
    },
    question_108: {
      question: 'In a Bundestag election in Germany, everyone may vote who ...',
      answer_a: 'lives in the Federal Republic of Germany and wants to vote.',
      answer_b: 'is a citizen of the Federal Republic of Germany and is at least 18 years old.',
      answer_c: 'has lived in the Federal Republic of Germany for at least 3 years.',
      answer_d: 'is a citizen of the Federal Republic of Germany and is at least 21 years old.'
    },
    question_109: {
      question: 'How often are Bundestag elections normally held in Germany?',
      answer_a: 'every three years',
      answer_b: 'every four years',
      answer_c: 'every five years',
      answer_d: 'every six years'
    },
    question_110: {
      question: 'For how many years is the Bundestag elected in Germany?',
      answer_a: '2 years',
      answer_b: '3 years',
      answer_c: '4 years',
      answer_d: '5 years'
    },
    question_111: {
      question: 'Which actions relating to the state of Israel are prohibited in Germany?',
      answer_a: "publicly criticizing Israel's policies",
      answer_b: 'hanging an Israeli flag on private property',
      answer_c: "discussing Israel's policies",
      answer_d: 'publicly calling for the destruction of Israel'
    },
    question_112: {
      question: 'Elections in Germany are ...',
      answer_a: 'special.',
      answer_b: 'secret.',
      answer_c: 'profession-related.',
      answer_d: 'gender-dependent.'
    },
    question_113: {
      question: 'In Germany, the party that wins an election is the one that ...',
      answer_a: 'receives the most votes.',
      answer_b: 'was voted for by a majority of men.',
      answer_c: 'received the most votes among workers.',
      answer_d: 'received the most first votes for its chancellor candidate.'
    },
    question_114: {
      question: 'Taking part in democratic elections in Germany is ...',
      answer_a: 'an obligation.',
      answer_b: 'a right.',
      answer_c: 'a compulsion.',
      answer_d: 'a burden.'
    },
    question_115: {
      question: 'What does "active right to vote" mean in Germany?',
      answer_a: 'One can be elected.',
      answer_b: 'One must go and vote.',
      answer_c: 'One can vote.',
      answer_d: 'One must attend the counting of the votes.'
    },
    question_116: {
      question: 'If you are allowed to vote in a Bundestag election in Germany, this is called ...',
      answer_a: 'active election campaign.',
      answer_b: 'active electoral procedure.',
      answer_c: 'active campaigning.',
      answer_d: 'the active right to vote.'
    },
    question_117: {
      question: 'What minimum percentage of second votes must parties receive to be elected to the German Bundestag?',
      answer_a: '3%',
      answer_b: '4%',
      answer_c: '5%',
      answer_d: '6%'
    },
    question_118: {
      question: 'Who may become a member of the roughly 40 Jewish Maccabi sports clubs?',
      answer_a: 'only Germans',
      answer_b: 'only Israelis',
      answer_c: 'only religious people',
      answer_d: 'everyone'
    },
    question_119: {
      question: 'Elections in Germany are free. What does this mean?',
      answer_a: 'All convicted criminals are not allowed to vote.',
      answer_b: 'If I want to go and vote, my employer must give me time off.',
      answer_c:
        'Every person can decide, without being forced, whether they want to vote and who they want to vote for.',
      answer_d: 'I can freely decide where I want to go and vote.'
    },
    question_120: {
      question: 'The electoral system in Germany is a ...',
      answer_a: 'census-based suffrage.',
      answer_b: 'three-class franchise.',
      answer_c: 'system combining majority and proportional representation.',
      answer_d: 'universal male suffrage.'
    },
    question_121: {
      question:
        'A party wants to enter the German Bundestag. However, it must reach a minimum share of voter support. This is called the ...',
      answer_a: '5% threshold.',
      answer_b: 'admission limit.',
      answer_c: 'base value.',
      answer_d: 'guideline.'
    },
    question_122: {
      question: 'What principle do elections in Germany follow? Elections in Germany are ...',
      answer_a: 'free, equal, secret.',
      answer_b: 'open, secure, free.',
      answer_c: 'closed, equal, secure.',
      answer_d: 'secure, open, voluntary.'
    },
    question_123: {
      question: 'What is the "5% threshold" in Germany?',
      answer_a: 'a voting rule in the Bundestag for small parties',
      answer_b: 'an attendance check in the Bundestag for votes',
      answer_c: 'the minimum share of voter support needed to enter parliament',
      answer_d: 'an attendance check in the Bundesrat for votes'
    },
    question_124: {
      question: 'The Bundestag election in Germany is the election ...',
      answer_a: 'of the Federal Chancellor.',
      answer_b: 'of the state parliaments.',
      answer_c: 'of the parliament for Germany.',
      answer_d: 'of the Federal President.'
    },
    question_125: {
      question: 'In a democracy, one function of regular elections is ...',
      answer_a: 'to force citizens to cast their vote.',
      answer_b: 'to enable a change of government according to the will of the majority of voters.',
      answer_c: "to keep the country's existing laws in place.",
      answer_d: 'to give the poor more power.'
    },
    question_126: {
      question: 'What do eligible citizens in Germany receive before an election?',
      answer_a: 'a polling notification from the municipality',
      answer_b: 'a voting permit from the Federal President',
      answer_c: 'a notification from the Federal Convention',
      answer_d: 'a notification from the parish office'
    },
    question_127: {
      question:
        'Why does the 5% threshold exist in the electoral law of the Federal Republic of Germany? It exists because ...',
      answer_a: 'the platforms of many small parties have a lot in common.',
      answer_b: 'citizens can lose track when there are too many small parties.',
      answer_c: 'many small parties make forming a government more difficult.',
      answer_d: 'small parties do not have enough money to pay their politicians.'
    },
    question_128: {
      question: 'Members of parliament who are elected by the citizens are called ...',
      answer_a: 'members of parliament.',
      answer_b: 'chancellors.',
      answer_c: 'ambassadors.',
      answer_d: 'Minister-Presidents.'
    },
    question_129: {
      question: 'In Germany, the people directly elect ...',
      answer_a: 'the Federal Chancellor.',
      answer_b: 'the Minister-President of a federal state.',
      answer_c: 'the Bundestag.',
      answer_d: 'the Federal President.'
    },
    question_130: {
      question:
        'Which ballot paper would be valid in a Bundestag election? Based on the Federal Electoral Regulation (BWO), Annex 26',
      answer_a: '1',
      answer_b: '2',
      answer_c: '3',
      answer_d: '4'
    },
    question_131: {
      question: 'In Germany, a mayor is ...',
      answer_a: 'the head of a school.',
      answer_b: 'the head of a bank.',
      answer_c: 'the head of a municipality.',
      answer_d: 'the chairperson of a party.'
    },
    question_132: {
      question: 'Many people in Germany do voluntary work in their free time. What does this mean?',
      answer_a: 'They work as soldiers.',
      answer_b: 'They work voluntarily and without pay in clubs and associations.',
      answer_c: 'They work in the Federal Government.',
      answer_d: 'They work in a hospital and earn money doing so.'
    },
    question_133: {
      question: 'What is permitted in Bundestag and state parliament elections in Germany?',
      answer_a: 'The husband also votes on behalf of his wife.',
      answer_b: "One can cast one's vote by postal ballot.",
      answer_c: "One can cast one's vote by phone on election day.",
      answer_d: 'Children from the age of 14 are allowed to vote.'
    },
    question_134: {
      question:
        'There are plans to discontinue the bus line you always take to work. What can you do to keep the bus line?',
      answer_a: "I join a citizens' initiative to preserve the bus line, or start one myself.",
      answer_b: 'I become a member of a sports club and take up cycling.',
      answer_c: 'I contact the tax office, because as a taxpayer I have a right to the bus line.',
      answer_d: "I write a letter to the municipality's forestry office."
    },
    question_135: {
      question: 'Who do trade unions represent in Germany?',
      answer_a: 'large companies',
      answer_b: 'small companies',
      answer_c: 'self-employed people',
      answer_d: 'employees'
    },
    question_136: {
      question: 'In Germany, you go to the labor court in the case of ...',
      answer_a: 'an incorrect utility bill statement.',
      answer_b: 'an unjustified dismissal by your boss.',
      answer_c: 'problems with your neighbors.',
      answer_d: 'difficulties following a traffic accident.'
    },
    question_137: {
      question: 'Which court is responsible in Germany for disputes in the workplace?',
      answer_a: 'the family court',
      answer_b: 'the criminal court',
      answer_c: 'the labor court',
      answer_d: 'the local court'
    },
    question_138: {
      question: 'What can I do in Germany if my employer has dismissed me unjustly?',
      answer_a: 'keep working and stay friendly toward my boss',
      answer_b: 'initiate a dunning procedure against the employer',
      answer_c: 'file an unfair dismissal claim',
      answer_d: 'report the employer to the police'
    },
    question_139: {
      question: 'When does a trial take place in court in Germany? When someone ...',
      answer_a: 'converts to another religion.',
      answer_b: 'has committed a crime and is charged.',
      answer_c: 'holds an opinion different from that of the government.',
      answer_d: 'has parked their car incorrectly and it is towed away.'
    },
    question_140: {
      question: 'What does a lay judge do in Germany? They ...',
      answer_a: 'decide together with judges on guilt and punishment.',
      answer_b: 'give citizens legal advice.',
      answer_c: 'issue official certificates.',
      answer_d: 'defend the accused.'
    },
    question_141: {
      question: 'Who in Germany advises people on legal matters and represents them in court?',
      answer_a: 'a lawyer',
      answer_b: 'a judge',
      answer_c: 'a lay judge',
      answer_d: 'a public prosecutor'
    },
    question_142: {
      question: 'What is the main task of a judge in Germany? A judge ...',
      answer_a: 'represents citizens in court.',
      answer_b: 'works at a court and delivers verdicts.',
      answer_c: 'changes laws.',
      answer_d: 'supports young people in court.'
    },
    question_143: {
      question: 'A judge in Germany belongs to the ...',
      answer_a: 'judiciary.',
      answer_b: 'executive.',
      answer_c: 'operative branch.',
      answer_d: 'legislature.'
    },
    question_144: {
      question: 'A judge in Germany belongs to the ...',
      answer_a: 'executive branch.',
      answer_b: 'judicial branch.',
      answer_c: 'planning branch.',
      answer_d: 'legislative branch.'
    },
    question_145: {
      question:
        'In Germany, state power is divided among separate branches. Which branch of state power does a judge work for? The ...',
      answer_a: 'judiciary',
      answer_b: 'executive',
      answer_c: 'press',
      answer_d: 'legislature'
    },
    question_146: {
      question: 'What is a court proceeding called in Germany?',
      answer_a: 'program',
      answer_b: 'procedure',
      answer_c: 'protocol',
      answer_d: 'trial'
    },
    question_147: {
      question: 'What is the job of a judge in Germany?',
      answer_a: 'to govern Germany',
      answer_b: 'to administer justice',
      answer_c: 'to draw up plans',
      answer_d: 'to enact laws'
    },
    question_148: {
      question: 'What is one task of the police in Germany?',
      answer_a: 'to defend the country',
      answer_b: 'to wiretap citizens',
      answer_c: 'to pass laws',
      answer_d: 'to monitor compliance with laws'
    },
    question_149: {
      question: 'What is an example of antisemitic behavior?',
      answer_a: 'attending a Jewish festival',
      answer_b: 'criticizing the Israeli government',
      answer_c: 'denying the Holocaust',
      answer_d: 'playing football against Jews.'
    },
    question_150: {
      question: 'A lay judge in Germany is ...',
      answer_a: 'the deputy head of the city.',
      answer_b: 'a volunteer judge.',
      answer_c: 'a member of a municipal council.',
      answer_d: 'a person who has studied law.'
    },
    question_151: {
      question: 'Who built the Wall in Berlin?',
      answer_a: 'Great Britain',
      answer_b: 'the GDR',
      answer_c: 'the Federal Republic of Germany',
      answer_d: 'the USA'
    },
    question_152: {
      question: 'When were the Nazis under Adolf Hitler in power in Germany?',
      answer_a: '1918 to 1923',
      answer_b: '1932 to 1950',
      answer_c: '1933 to 1945',
      answer_d: '1945 to 1989'
    },
    question_153: {
      question: 'What happened on May 8, 1945?',
      answer_a: 'Death of Adolf Hitler',
      answer_b: 'Start of the construction of the Berlin Wall',
      answer_c: 'Election of Konrad Adenauer as Federal Chancellor',
      answer_d: 'End of the Second World War in Europe'
    },
    question_154: {
      question: 'When did the Second World War end?',
      answer_a: '1933',
      answer_b: '1945',
      answer_c: '1949',
      answer_d: '1961'
    },
    question_155: {
      question: 'When were the Nazis in power in Germany?',
      answer_a: '1888 to 1918',
      answer_b: '1921 to 1934',
      answer_c: '1933 to 1945',
      answer_d: '1949 to 1963'
    },
    question_156: {
      question: 'In what year did Hitler become Reich Chancellor?',
      answer_a: '1923',
      answer_b: '1927',
      answer_c: '1933',
      answer_d: '1936'
    },
    question_157: {
      question: 'In 1933, the Nazis under Adolf Hitler established ... in Germany.',
      answer_a: 'a dictatorship.',
      answer_b: 'a democratic state.',
      answer_c: 'a monarchy.',
      answer_d: 'a principality.'
    },
    question_158: {
      question: 'The "Third Reich" was a ...',
      answer_a: 'dictatorship.',
      answer_b: 'democracy.',
      answer_c: 'monarchy.',
      answer_d: 'council republic.'
    },
    question_159: {
      question: 'What did NOT exist in Germany during the time of National Socialism?',
      answer_a: 'free elections',
      answer_b: 'press censorship',
      answer_c: 'arbitrary arrests',
      answer_d: 'persecution of Jews'
    },
    question_160: {
      question: 'Which war lasted from 1939 to 1945?',
      answer_a: 'the First World War',
      answer_b: 'the Second World War',
      answer_c: 'the Vietnam War',
      answer_d: 'the Gulf War'
    },
    question_161: {
      question: 'What characterized the Nazi state? A policy ...',
      answer_a: 'of state racism',
      answer_b: 'of freedom of expression',
      answer_c: 'of general religious freedom',
      answer_d: 'of the development of democracy'
    },
    question_162: {
      question: 'Claus Schenk Graf von Stauffenberg became known for ...',
      answer_a: 'winning a gold medal at the 1936 Olympic Games.',
      answer_b: 'building the Reichstag building.',
      answer_c: 'building up the Wehrmacht.',
      answer_d: 'the assassination attempt on Hitler on July 20, 1944.'
    },
    question_163: {
      question: 'In what year did the Nazis destroy synagogues and Jewish shops in Germany?',
      answer_a: '1925',
      answer_b: '1930',
      answer_c: '1938',
      answer_d: '1945'
    },
    question_164: {
      question: 'What happened on November 9, 1938 in Germany?',
      answer_a: 'The Second World War begins with the attack on Poland.',
      answer_b: 'The Nazis lose an election and dissolve the Reichstag.',
      answer_c: 'Jewish shops and synagogues are destroyed by the Nazis and their supporters.',
      answer_d: 'Hitler becomes Reich President and bans all parties.'
    },
    question_165: {
      question: 'What was the name of the first Federal Chancellor of the Federal Republic of Germany?',
      answer_a: 'Konrad Adenauer',
      answer_b: 'Kurt Georg Kiesinger',
      answer_c: 'Helmut Schmidt',
      answer_d: 'Willy Brandt'
    },
    question_166: {
      question: 'At which demonstrations in Germany did people chant "We are the people"?',
      answer_a: "at the workers' uprising in 1953 in the GDR",
      answer_b: 'at the demonstrations in 1968 in the Federal Republic of Germany',
      answer_c: 'at the anti-nuclear-power demonstrations in 1985 in the Federal Republic of Germany',
      answer_d: 'at the Monday demonstrations in 1989 in the GDR'
    },
    question_167: {
      question:
        'Which countries were referred to as the "Allied occupying powers" in Germany after the Second World War?',
      answer_a: 'Soviet Union, Great Britain, Poland, Sweden',
      answer_b: 'France, Soviet Union, Italy, Japan',
      answer_c: 'USA, Soviet Union, Spain, Portugal',
      answer_d: 'USA, Soviet Union, Great Britain, France'
    },
    question_168: {
      question: 'Which country was not an "Allied occupying power" in Germany?',
      answer_a: 'USA',
      answer_b: 'Soviet Union',
      answer_c: 'France',
      answer_d: 'Japan'
    },
    question_169: {
      question: 'When was the Federal Republic of Germany founded?',
      answer_a: '1939',
      answer_b: '1945',
      answer_c: '1949',
      answer_d: '1951'
    },
    question_170: {
      question: 'What existed in Germany during the time of National Socialism?',
      answer_a: 'the banning of parties',
      answer_b: "the right to the free development of one's personality",
      answer_c: 'freedom of the press',
      answer_d: 'the protection of human dignity'
    },
    question_171: {
      question: 'Social market economy means the economy ...',
      answer_a: 'regulates itself solely according to supply and demand.',
      answer_b: 'is planned and controlled by the state, with no regard for supply and demand.',
      answer_c: 'is oriented toward demand from abroad.',
      answer_d: 'is oriented toward supply and demand, but the state ensures social balance.'
    },
    question_172: {
      question: 'In which occupation zone was the GDR founded? In the ...',
      answer_a: 'American occupation zone',
      answer_b: 'French occupation zone',
      answer_c: 'British occupation zone',
      answer_d: 'Soviet occupation zone'
    },
    question_173: {
      question: 'The Federal Republic of Germany is a founding member ...',
      answer_a: 'of the North Atlantic Treaty Organization (NATO).',
      answer_b: 'of the United Nations (UN).',
      answer_c: 'of the European Union (EU).',
      answer_d: 'of the Warsaw Pact.'
    },
    question_174: {
      question: 'When was the GDR founded?',
      answer_a: '1947',
      answer_b: '1949',
      answer_c: '1953',
      answer_d: '1956'
    },
    question_175: {
      question: 'How many occupation zones were there in Germany after the Second World War?',
      answer_a: '3',
      answer_b: '4',
      answer_c: '5',
      answer_d: '6'
    },
    question_176: {
      question: "How were Germany's occupation zones distributed after 1945?",
      answer_a: '1 = Great Britain, 2 = Soviet Union, 3 = France, 4 = USA',
      answer_b: '1 = Soviet Union, 2 = Great Britain, 3 = USA, 4 = France',
      answer_c: '1 = Great Britain, 2 = Soviet Union, 3 = USA, 4 = France',
      answer_d: '1 = Great Britain, 2 = USA, 3 = Soviet Union, 4 = France'
    },
    question_177: {
      question: 'Which German city was divided into four sectors after the Second World War?',
      answer_a: 'Munich',
      answer_b: 'Berlin',
      answer_c: 'Dresden',
      answer_d: 'Frankfurt an der Oder'
    },
    question_178: {
      question:
        'From June 1948 to May 1949, the citizens of West Berlin were supplied by an airlift. What circumstance was responsible for this?',
      answer_a: 'For France, supplying the West Berlin population by airplane was more cost-effective.',
      answer_b: 'The American soldiers were afraid of attacks during transport by land.',
      answer_c: 'For Great Britain, supplying the city via the airlift was faster.',
      answer_d: 'The Soviet Union cut off all traffic by land.'
    },
    question_179: {
      question: 'How did the Second World War in Europe officially end?',
      answer_a: 'with the death of Adolf Hitler',
      answer_b: "through Germany's unconditional surrender",
      answer_c: 'with the withdrawal of the Germans from the occupied territories',
      answer_d: 'through a revolution in Germany'
    },
    question_180: {
      question: 'The first Federal Chancellor of the Federal Republic of Germany was ...',
      answer_a: 'Ludwig Erhard.',
      answer_b: 'Willy Brandt.',
      answer_c: 'Konrad Adenauer.',
      answer_d: 'Gerhard Schröder.'
    },
    question_181: {
      question:
        'What did Willy Brandt want to express with his kneeling gesture in 1970 in the former Jewish ghetto in Warsaw?',
      answer_a: 'He was submitting to the former Allies.',
      answer_b: 'He was asking Poland and the Polish Jews for forgiveness.',
      answer_c: 'He was showing his humility before the Warsaw Pact.',
      answer_d: 'He was saying a prayer at the grave of the Unknown Soldier.'
    },
    question_182: {
      question: 'What is the Jewish house of prayer called?',
      answer_a: 'Basilica',
      answer_b: 'Mosque',
      answer_c: 'Synagogue',
      answer_d: 'Church'
    },
    question_183: {
      question: 'When was the "economic miracle" in the Federal Republic of Germany?',
      answer_a: 'the 1940s',
      answer_b: 'the 1950s',
      answer_c: 'the 1970s',
      answer_d: 'the 1980s'
    },
    question_184: {
      question: 'On what legal basis was the State of Israel founded?',
      answer_a: 'a resolution of the United Nations',
      answer_b: 'a resolution of the Zionist Congress',
      answer_c: 'a proposal by the Federal Government',
      answer_d: 'a proposal by the USSR'
    },
    question_185: {
      question: 'What did the term "Iron Curtain" stand for? The isolation of ...',
      answer_a: 'the Warsaw Pact from the West',
      answer_b: 'northern Germany from southern Germany',
      answer_c: 'Nazi Germany from the Allies',
      answer_d: 'Europe from the USA'
    },
    question_186: {
      question:
        'In 1953 there was an uprising in the GDR that was commemorated by a public holiday in the Federal Republic of Germany for a long time. When was that?',
      answer_a: 'May 1',
      answer_b: 'June 17',
      answer_c: 'July 20',
      answer_d: 'November 9'
    },
    question_187: {
      question: 'Which German state had a black-red-gold flag with a hammer, compass, and wreath of grain?',
      answer_a: 'Prussia',
      answer_b: 'Federal Republic of Germany',
      answer_c: '"Third Reich"',
      answer_d: 'GDR'
    },
    question_188: {
      question: 'In what year was the Wall in Berlin built?',
      answer_a: '1953',
      answer_b: '1956',
      answer_c: '1959',
      answer_d: '1961'
    },
    question_189: {
      question: 'When did the GDR build the Wall in Berlin?',
      answer_a: '1919',
      answer_b: '1933',
      answer_c: '1961',
      answer_d: '1990'
    },
    question_190: {
      question: 'What does the abbreviation GDR stand for?',
      answer_a: 'Third German Radio',
      answer_b: 'The German Republic',
      answer_c: 'Third German Republic',
      answer_d: 'German Democratic Republic'
    },
    question_191: {
      question: 'When was the Wall in Berlin opened for everyone?',
      answer_a: '1987',
      answer_b: '1989',
      answer_c: '1992',
      answer_d: '1995'
    },
    question_192: {
      question: 'Which present-day German federal state used to belong to the territory of the GDR?',
      answer_a: 'Brandenburg',
      answer_b: 'Bavaria',
      answer_c: 'Saarland',
      answer_d: 'Hesse'
    },
    question_193: {
      question: 'From 1961 to 1989, Berlin was ...',
      answer_a: 'without a mayor.',
      answer_b: 'its own separate state.',
      answer_c: 'divided by a wall.',
      answer_d: 'reachable only by airplane.'
    },
    question_194: {
      question: 'On October 3, Germany celebrates the Day of German ...',
      answer_a: 'Unity.',
      answer_b: 'Nation.',
      answer_c: 'Federal States.',
      answer_d: 'Cities.'
    },
    question_195: {
      question: 'Which present-day German federal state used to belong to the territory of the GDR?',
      answer_a: 'Hesse',
      answer_b: 'Saxony-Anhalt',
      answer_c: 'North Rhine-Westphalia',
      answer_d: 'Saarland'
    },
    question_196: {
      question:
        'Why is the period in the fall of 1989 in the GDR called "Die Wende" ("the turning point")? During this time, the GDR changed politically ...',
      answer_a: 'from a dictatorship to a democracy.',
      answer_b: 'from a liberal market economy to socialism.',
      answer_c: 'from a monarchy to social democracy.',
      answer_d: 'from a religious state to a communist state.'
    },
    question_197: {
      question: 'Which present-day German federal state used to belong to the territory of the GDR?',
      answer_a: 'Thuringia',
      answer_b: 'Hesse',
      answer_c: 'Bavaria',
      answer_d: 'Bremen'
    },
    question_198: {
      question: 'Which present-day German federal state used to belong to the territory of the GDR?',
      answer_a: 'Bavaria',
      answer_b: 'Lower Saxony',
      answer_c: 'Saxony',
      answer_d: 'Baden-Württemberg'
    },
    question_199: {
      question: 'In the GDR, the abbreviation "Stasi" referred to ...',
      answer_a: 'the parliament.',
      answer_b: 'the Ministry for State Security.',
      answer_c: 'a ruling party.',
      answer_d: 'the Ministry of Education.'
    },
    question_200: {
      question: 'Which present-day German federal state used to belong to the territory of the GDR?',
      answer_a: 'Hesse',
      answer_b: 'Schleswig-Holstein',
      answer_c: 'Mecklenburg-Vorpommern',
      answer_d: 'Saarland'
    },
    question_201: {
      question:
        'Which of the following lists contains only federal states that belonged to the territory of the former GDR?',
      answer_a: 'Lower Saxony, North Rhine-Westphalia, Hesse, Schleswig-Holstein, Brandenburg',
      answer_b: 'Mecklenburg-Western Pomerania, Brandenburg, Saxony, Saxony-Anhalt, Thuringia',
      answer_c: 'Bavaria, Baden-Württemberg, Rhineland-Palatinate, Thuringia, Saxony',
      answer_d: 'Saxony, Thuringia, Hesse, Lower Saxony, Brandenburg'
    },
    question_202: {
      question: 'Which side did the GDR belong to during the "Cold War"?',
      answer_a: 'to the Western powers',
      answer_b: 'to the Warsaw Pact',
      answer_c: 'to NATO',
      answer_d: 'to the non-aligned states'
    },
    question_203: {
      question: "What was the GDR's economic system called?",
      answer_a: 'market economy',
      answer_b: 'planned economy',
      answer_c: 'supply and demand',
      answer_d: 'capitalism'
    },
    question_204: {
      question: 'How did the Federal Republic of Germany and the GDR become a single state?',
      answer_a: 'The Federal Republic occupied the GDR.',
      answer_b: "Today's five eastern federal states joined the Federal Republic of Germany.",
      answer_c: 'The western federal states joined the GDR.',
      answer_d: 'The GDR occupied the Federal Republic of Germany.'
    },
    question_205: {
      question:
        "With the GDR's accession to the Federal Republic of Germany, the new federal states now also belong ...",
      answer_a: 'to the European Union.',
      answer_b: 'to the Warsaw Pact.',
      answer_c: 'to OPEC.',
      answer_d: 'to the European Defence Community.'
    },
    question_206: {
      question: 'What do the so-called "Stolpersteine" (stumbling stones) in Germany commemorate?',
      answer_a: 'famous German politicians',
      answer_b: 'the victims of National Socialism',
      answer_c: 'traffic accident victims',
      answer_d: 'well-known Jewish musicians'
    },
    question_207: {
      question: 'Which military alliance was the GDR a member of?',
      answer_a: 'NATO',
      answer_b: 'the Confederation of the Rhine',
      answer_c: 'the Warsaw Pact',
      answer_d: 'the European Alliance'
    },
    question_208: {
      question: 'What was the "Stasi"?',
      answer_a: 'the secret service of the "Third Reich"',
      answer_b: 'a famous German memorial site',
      answer_c: 'the secret service of the GDR',
      answer_d: 'a German sports club during the Second World War'
    },
    question_209: {
      question: 'Which of these was the coat of arms of the German Democratic Republic?',
      answer_a: 'Image 1',
      answer_b: 'Image 2',
      answer_c: 'Image 3',
      answer_d: 'Image 4'
    },
    question_210: {
      question: 'What happened on 17 June 1953 in the GDR?',
      answer_a: 'the ceremonial accession to the Warsaw Pact',
      answer_b: 'nationwide strikes and a popular uprising',
      answer_c: 'the 1st SED party congress',
      answer_d: 'the first visit by Fidel Castro'
    },
    question_211: {
      question: 'Which politician is associated with the "Ostverträge" (Eastern Treaties)?',
      answer_a: 'Helmut Kohl',
      answer_b: 'Willy Brandt',
      answer_c: 'Mikhail Gorbachev',
      answer_d: 'Ludwig Erhard'
    },
    question_212: {
      question: "What is Germany's full official name?",
      answer_a: 'Federal State of Germany',
      answer_b: 'Federal States of Germany',
      answer_c: 'Federal Republic of Germany',
      answer_d: 'Federal District of Germany'
    },
    question_213: {
      question: 'How many inhabitants does Germany have?',
      answer_a: '70 million',
      answer_b: '78 million',
      answer_c: '84 million',
      answer_d: '90 million'
    },
    question_214: {
      question: 'What colors does the German flag have?',
      answer_a: 'black-red-gold',
      answer_b: 'red-white-black',
      answer_c: 'black-red-green',
      answer_d: 'black-yellow-red'
    },
    question_215: {
      question: 'Who is referred to as the "Chancellor of German Unity"?',
      answer_a: 'Gerhard Schröder',
      answer_b: 'Helmut Kohl',
      answer_c: 'Konrad Adenauer',
      answer_d: 'Helmut Schmidt'
    },
    question_216: {
      question: 'Which symbol can be seen in the plenary hall of the German Bundestag?',
      answer_a: 'the Federal Eagle',
      answer_b: 'the flag of the city of Berlin',
      answer_c: 'the Reich Eagle',
      answer_d: 'the Imperial Crown'
    },
    question_217: {
      question: 'During which period did the German Democratic Republic (GDR) exist?',
      answer_a: '1919 to 1927',
      answer_b: '1933 to 1945',
      answer_c: '1945 to 1961',
      answer_d: '1949 to 1990'
    },
    question_218: {
      question: 'How many federal states were added to the Federal Republic of Germany during reunification in 1990?',
      answer_a: '4',
      answer_b: '5',
      answer_c: '6',
      answer_d: '7'
    },
    question_219: {
      question: "The Federal Republic of Germany has had today's borders since ...",
      answer_a: '1933',
      answer_b: '1949',
      answer_c: '1971',
      answer_d: '1990'
    },
    question_220: {
      question: '27 January is an official day of remembrance in Germany. What does this day commemorate?',
      answer_a: 'the end of the Second World War',
      answer_b: 'the adoption of the Basic Law',
      answer_c: 'the reunification of Germany',
      answer_d: 'the victims of National Socialism (the day of the liberation of the Auschwitz extermination camp)'
    },
    question_221: {
      question: 'Germany is a member of the Schengen Agreement. What does this mean?',
      answer_a: 'Germans can travel to many European countries without passport control.',
      answer_b: 'Anyone can enter Germany without an identity check.',
      answer_c: 'Germans can travel to any country without passport control.',
      answer_d: 'Germans can pay with the euro in every country.'
    },
    question_222: {
      question: 'Which country is a neighboring country of Germany?',
      answer_a: 'Hungary',
      answer_b: 'Portugal',
      answer_c: 'Spain',
      answer_d: 'Switzerland'
    },
    question_223: {
      question: 'Which country is a neighboring country of Germany?',
      answer_a: 'Romania',
      answer_b: 'Bulgaria',
      answer_c: 'Poland',
      answer_d: 'Greece'
    },
    question_224: {
      question: 'What does the abbreviation EU stand for?',
      answer_a: 'European Enterprises',
      answer_b: 'European Union',
      answer_c: 'Unified Union',
      answer_d: 'Euro Union'
    },
    question_225: {
      question: 'In which other country is there a large German-speaking population?',
      answer_a: 'Czech Republic',
      answer_b: 'Norway',
      answer_c: 'Spain',
      answer_d: 'Austria'
    },
    question_226: {
      question: 'Which of these is the flag of the European Union?',
      answer_a: 'Image 1',
      answer_b: 'Image 2',
      answer_c: 'Image 3',
      answer_d: 'Image 4'
    },
    question_227: {
      question: 'Which country is a neighboring country of Germany?',
      answer_a: 'Finland',
      answer_b: 'Denmark',
      answer_c: 'Norway',
      answer_d: 'Sweden'
    },
    question_228: {
      question: "What is the GDR's accession to the Federal Republic of Germany in 1990 generally called?",
      answer_a: 'NATO eastward enlargement',
      answer_b: 'EU eastward enlargement',
      answer_c: 'German reunification',
      answer_d: 'European Community'
    },
    question_229: {
      question: 'Which country is a neighboring country of Germany?',
      answer_a: 'Spain',
      answer_b: 'Bulgaria',
      answer_c: 'Norway',
      answer_d: 'Luxembourg'
    },
    question_230: {
      question: 'The European Parliament is elected on a regular basis, namely every ...',
      answer_a: '5 years.',
      answer_b: '6 years.',
      answer_c: '7 years.',
      answer_d: '8 years.'
    },
    question_231: {
      question: 'What does the term "European integration" mean?',
      answer_a: 'It refers to American immigrants in Europe.',
      answer_b: 'The term refers to a halt on immigration to Europe.',
      answer_c: 'It refers to European emigrants in the USA.',
      answer_d: 'The term refers to European states joining together to form the EU.'
    },
    question_232: {
      question: 'Who is elected in the European election?',
      answer_a: 'the European Commission',
      answer_b: 'the countries that are allowed to join the EU',
      answer_c: 'the members of the European Parliament',
      answer_d: 'the European constitution'
    },
    question_233: {
      question: 'Which country is a neighboring country of Germany?',
      answer_a: 'Czech Republic',
      answer_b: 'Bulgaria',
      answer_c: 'Greece',
      answer_d: 'Portugal'
    },
    question_234: {
      question: 'Where is one seat of the European Parliament?',
      answer_a: 'London',
      answer_b: 'Paris',
      answer_c: 'Berlin',
      answer_d: 'Strasbourg'
    },
    question_235: {
      question:
        'The then French President François Mitterrand and the then German Federal Chancellor Helmut Kohl jointly commemorate the dead of both world wars in Verdun. Which goal of the European Union becomes clear at this meeting?',
      answer_a: 'Friendship between England and Germany',
      answer_b: 'Freedom to travel to all EU countries',
      answer_c: 'Peace and security in the EU countries',
      answer_d: 'Uniform public holidays in the EU countries'
    },
    question_236: {
      question: 'How many member states does the EU have today?',
      answer_a: '21',
      answer_b: '23',
      answer_c: '25',
      answer_d: '27'
    },
    question_237: {
      question:
        'In 2007, the 50th anniversary of the "Treaties of Rome" was celebrated. What was the content of the treaties?',
      answer_a: "Germany's accession to NATO",
      answer_b: 'The founding of the European Economic Community (EEC)',
      answer_c: "Germany's obligation to pay reparations",
      answer_d: 'The establishment of the Oder-Neisse line as the eastern border'
    },
    question_238: {
      question: 'In which locations does the European Parliament work?',
      answer_a: 'Paris, London and The Hague',
      answer_b: 'Strasbourg, Luxembourg and Brussels',
      answer_c: 'Rome, Bern and Vienna',
      answer_d: 'Bonn, Zurich and Milan'
    },
    question_239: {
      question:
        'Through which treaties did the Federal Republic of Germany join with other states to form the European Economic Community?',
      answer_a: 'through the "Treaties of Hamburg"',
      answer_b: 'through the "Treaties of Rome"',
      answer_c: 'through the "Treaties of Paris"',
      answer_d: 'through the "Treaties of London"'
    },
    question_240: {
      question: 'Since when has cash payment in euros been used in Germany?',
      answer_a: '1995',
      answer_b: '1998',
      answer_c: '2002',
      answer_d: '2005'
    },
    question_241: {
      question: 'Mrs. Seger is having a baby. What must she do to receive parental allowance?',
      answer_a: 'She must write to her health insurance fund.',
      answer_b: 'She must submit an application to the parental allowance office.',
      answer_c: "She doesn't have to do anything, because she automatically receives parental allowance.",
      answer_d: 'She must ask the employment office for permission.'
    },
    question_242: {
      question: 'Who decides whether a child in Germany goes to kindergarten?',
      answer_a: 'the state',
      answer_b: 'the federal states',
      answer_c: 'the parents/legal guardians',
      answer_d: 'the schools'
    },
    question_243: {
      question:
        'Maik and Sybille want to hold a street demonstration with friends in their town in Germany. What must they do beforehand?',
      answer_a: 'They must register the demonstration.',
      answer_b: "They don't have to do anything. In Germany you may demonstrate anywhere at any time.",
      answer_c: "They can't do anything, because demonstrations are fundamentally prohibited in Germany.",
      answer_d: 'Maik and Sybille must found a new club, because only registered clubs are allowed to demonstrate.'
    },
    question_244: {
      question:
        'Which school-leaving qualification does one normally need in order to begin studying at a university in Germany?',
      answer_a: 'the Abitur',
      answer_b: 'a Diplom (diploma degree)',
      answer_c: 'power of procuration (Prokura)',
      answer_d: "a journeyman's examination"
    },
    question_245: {
      question: 'Who is not allowed to live together as a couple in Germany?',
      answer_a: 'Hans (20 years old) and Marie (19 years old)',
      answer_b: 'Tom (20 years old) and Klaus (45 years old)',
      answer_c: 'Sofie (35 years old) and Lisa (40 years old)',
      answer_d: 'Anne (13 years old) and Tim (25 years old)'
    },
    question_246: {
      question: 'From what age is a person legally an adult in Germany?',
      answer_a: '16',
      answer_b: '18',
      answer_c: '19',
      answer_d: '21'
    },
    question_247: {
      question:
        'A woman is pregnant. She is especially protected by law shortly before and after the birth of her child. What is this protection called?',
      answer_a: 'parental leave',
      answer_b: 'maternity protection',
      answer_c: 'childbirth preparation',
      answer_d: 'the postpartum period (Wochenbett)'
    },
    question_248: {
      question: 'In Germany, raising children is primarily the responsibility of ...',
      answer_a: 'the state.',
      answer_b: 'the parents.',
      answer_c: 'the grandparents.',
      answer_d: 'the schools.'
    },
    question_249: {
      question: 'Who is mainly responsible for raising children in Germany?',
      answer_a: 'the state',
      answer_b: 'the parents',
      answer_c: 'relatives',
      answer_d: 'the schools'
    },
    question_250: {
      question: 'In Germany, you have the best chances of getting a well-paid job if you ...',
      answer_a: 'are Catholic.',
      answer_b: 'are well educated.',
      answer_c: 'are a woman.',
      answer_d: 'are a member of a political party.'
    },
    question_251: {
      question: 'If a child is hit in Germany, ...',
      answer_a: "that is nobody's business.",
      answer_b: "that is only the family's business.",
      answer_c: 'the person cannot be punished for it.',
      answer_d: 'the person can be punished for it.'
    },
    question_252: {
      question: 'In Germany ...',
      answer_a: 'you may be married to only one partner at a time.',
      answer_b: 'you can have several spouses at the same time.',
      answer_c: 'you may not marry again once you have been married before.',
      answer_d: 'a woman may not remarry after her husband has died.'
    },
    question_253: {
      question: 'Where must you register when you move to a new home in Germany?',
      answer_a: "at the residents' registration office",
      answer_b: 'at the registry office',
      answer_c: 'at the public order office',
      answer_d: 'at the trade licensing office'
    },
    question_254: {
      question:
        'In Germany, married couples are allowed to get divorced. In most cases they must first observe the "year of separation". What does that mean?',
      answer_a: 'The divorce process takes one year.',
      answer_b: 'The spouses have been married for one year, then the divorce is possible.',
      answer_c: 'The right to visit the children applies for one year.',
      answer_d:
        'The spouses live separately and lead their own lives for at least one year. After that, the divorce is possible.'
    },
    question_255: {
      question: 'In Germany, parents can get help with parenting problems from the ...',
      answer_a: 'public order office.',
      answer_b: 'school authority.',
      answer_c: 'youth welfare office.',
      answer_d: 'public health office.'
    },
    question_256: {
      question: 'A married couple wants to open a restaurant in Germany. What do they absolutely need for this?',
      answer_a: 'permission from the police',
      answer_b: 'approval from a political party',
      answer_c: "approval from the residents' registration office",
      answer_d: 'a restaurant license from the responsible authority'
    },
    question_257: {
      question: 'An adult woman wants to complete her Abitur in Germany later in life. She can do this at ...',
      answer_a: 'a university.',
      answer_b: 'an evening secondary school (Abendgymnasium).',
      answer_c: 'a Hauptschule.',
      answer_d: 'a private university.'
    },
    question_258: {
      question: 'What is the youth welfare office in Germany allowed to do?',
      answer_a: 'It decides which school the child attends.',
      answer_b: 'It can remove a child who is being beaten or made to go hungry from the family.',
      answer_c: 'It pays child benefit to the parents.',
      answer_d: 'It checks whether the child attends a kindergarten.'
    },
    question_259: {
      question: 'The Career Information Center (BIZ) at the Federal Employment Agency in Germany helps with ...',
      answer_a: 'calculating pensions.',
      answer_b: 'finding an apprenticeship.',
      answer_c: 'tax returns.',
      answer_d: 'health insurance.'
    },
    question_260: {
      question: 'In Germany, a child at school has ...',
      answer_a: 'a right to unlimited free time.',
      answer_b: 'free choice of all subjects.',
      answer_c: 'an entitlement to school fees.',
      answer_d: 'a duty to attend.'
    },
    question_261: {
      question: 'A man wants to complete his Abitur at the age of 30 in Germany. Where can he do this? At ...',
      answer_a: 'a university.',
      answer_b: 'an evening secondary school (Abendgymnasium).',
      answer_c: 'a Hauptschule.',
      answer_d: 'a private university.'
    },
    question_262: {
      question: 'What does the principle of equal treatment mean in Germany?',
      answer_a: 'No one may be disadvantaged, for example because of a disability.',
      answer_b: 'You may disadvantage other people if there are sufficient personal reasons for doing so.',
      answer_c: 'No one may bring a lawsuit on behalf of people who have been disadvantaged.',
      answer_d: 'It is required by law for everyone to donate money to disadvantaged groups every year.'
    },
    question_263: {
      question:
        'In Germany, young people are criminally responsible from the age of 14. This means: young people aged 14 and older who violate criminal law ...',
      answer_a: 'are punished.',
      answer_b: 'are treated like adults.',
      answer_c: 'share the punishment with their parents.',
      answer_d: 'are not punished.'
    },
    question_264: {
      question: 'At which festival do people in Germany wear colorful costumes and masks?',
      answer_a: 'on Rosenmontag (Carnival Monday)',
      answer_b: 'on May Day',
      answer_c: 'at Oktoberfest',
      answer_d: 'at Pentecost'
    },
    question_265: {
      question: 'Where must you go first in Germany if you want to get married?',
      answer_a: "to the residents' registration office",
      answer_b: 'to the public order office',
      answer_c: 'to the employment agency',
      answer_d: 'to the registry office'
    },
    question_266: {
      question: 'When does the legally mandated nighttime quiet period begin in Germany?',
      answer_a: 'when the sun sets',
      answer_b: 'when the neighbors go to sleep',
      answer_c: 'at 0:00, midnight',
      answer_d: 'at 10 p.m.'
    },
    question_267: {
      question:
        "A young woman in Germany, 22 years old, lives together with her boyfriend. The woman's parents don't like this because they don't like the boyfriend. What can the parents do?",
      answer_a: 'They must respect the decision of their adult daughter.',
      answer_b: 'They have the right to bring their daughter back to the family home.',
      answer_c: 'They can go to the police and report their daughter.',
      answer_d: 'They look for a different man for their daughter.'
    },
    question_268: {
      question:
        "A young woman wants to get her driver's license. She is afraid of the exam because German is not her native language. What is correct?",
      answer_a: "She must live in Germany for at least ten years before she can get a driver's license.",
      answer_b: "If she doesn't speak German, she is not allowed to have a driver's license.",
      answer_c: "She must get her driver's license in the country where her native language is spoken.",
      answer_d:
        'She may be able to take the theory exam in her native language. There are more than ten languages to choose from.'
    },
    question_269: {
      question: 'In Germany, children from the age of three until they first start school are entitled to ...',
      answer_a: 'monthly pocket money.',
      answer_b: 'a place in a sports club.',
      answer_c: 'a place in a kindergarten.',
      answer_d: 'a holiday activity pass.'
    },
    question_270: {
      question: 'The Volkshochschule (adult education center) in Germany is an institution ...',
      answer_a: 'for religious instruction.',
      answer_b: 'only for young people.',
      answer_c: 'for continuing education.',
      answer_d: 'only for retirees.'
    },
    question_271: {
      question: 'What is a custom in Germany at Christmas?',
      answer_a: 'hiding colorful eggs',
      answer_b: 'decorating a Christmas tree',
      answer_c: 'dressing up in masks and costumes',
      answer_d: 'putting pumpkins in front of the door'
    },
    question_272: {
      question: 'Which way of life/living arrangement is not permitted in Germany?',
      answer_a: 'A man and a woman are divorced and each live with a new partner.',
      answer_b: 'Two women live together.',
      answer_c: 'A single father lives together with his two children.',
      answer_d: 'A man is married to two women at the same time.'
    },
    question_273: {
      question: 'For parenting problems, in Germany you go to ...',
      answer_a: 'a doctor.',
      answer_b: 'the public health office.',
      answer_c: "the residents' registration office.",
      answer_d: 'the youth welfare office.'
    },
    question_274: {
      question:
        'In Germany you have deliberately opened a letter addressed to another person. Which right have you failed to respect?',
      answer_a: 'the right to remain silent',
      answer_b: 'the privacy of correspondence',
      answer_c: 'the duty of confidentiality',
      answer_d: 'freedom of expression'
    },
    question_275: {
      question: 'What do you need for a divorce in Germany?',
      answer_a: 'the consent of the parents',
      answer_b: 'a certificate from a doctor',
      answer_c: 'the consent of the children',
      answer_d: 'the support of a lawyer'
    },
    question_276: {
      question: 'What should you do if you are treated badly by your contact person at a German government office?',
      answer_a: "I can't do anything.",
      answer_b: 'I have to put up with this treatment.',
      answer_c: 'I threaten the person.',
      answer_d: 'I can file a complaint with the head of the office.'
    },
    question_277: {
      question:
        'A woman with a two-year-old child applies for a job in Germany. What is an example of discrimination? She does not get the job for the sole reason that she ...',
      answer_a: 'does not speak English.',
      answer_b: 'has salary expectations that are too high.',
      answer_c: 'has no experience in this profession.',
      answer_d: 'is a mother.'
    },
    question_278: {
      question:
        'A man in a wheelchair has applied for a job as an accountant. What is an example of discrimination? He does not get the job for the sole reason that he ...',
      answer_a: 'uses a wheelchair.',
      answer_b: 'has no experience.',
      answer_c: 'has salary expectations that are too high.',
      answer_d: 'does not speak English.'
    },
    question_279: {
      question:
        'Most apartment buildings in Germany have "house rules" (Hausordnung). What is included in such "house rules"? They set out ...',
      answer_a: 'rules for using public transportation.',
      answer_b: 'all the tenants in the building.',
      answer_c: 'rules that all residents must follow.',
      answer_d: 'the address of the nearest public order office.'
    },
    question_280: {
      question: 'If you want to challenge an incorrect tax assessment in Germany, you must ...',
      answer_a: 'do nothing.',
      answer_b: 'throw the notice away.',
      answer_c: 'file an objection.',
      answer_d: 'wait until a different notice arrives.'
    },
    question_281: {
      question:
        'Two friends want to go to a public swimming pool in Germany. Both have dark skin and are refused entry because of it. Which right is being violated in this situation? The right to ...',
      answer_a: 'freedom of expression',
      answer_b: 'equal treatment',
      answer_c: 'freedom of assembly',
      answer_d: 'freedom of movement'
    },
    question_282: {
      question: 'Which honorary position must German citizens take on if asked to do so?',
      answer_a: 'club coach',
      answer_b: 'election helper',
      answer_c: 'library supervisor',
      answer_d: 'teacher'
    },
    question_283: {
      question: 'What do you do if you receive an incorrect invoice from a German government office?',
      answer_a: 'I leave the invoice as it is.',
      answer_b: 'I file an objection with the authority.',
      answer_c: 'I send the invoice back to the authority.',
      answer_d: 'I take the invoice to the tax office.'
    },
    question_284: {
      question:
        'What you need to know for work is going to change very quickly in the future. What can be done about this?',
      answer_a: "It doesn't matter what you learn.",
      answer_b: 'Adults must keep on learning even after their training is complete.',
      answer_c:
        'Children learn everything important for their career at school. After school, there is no need to keep learning.',
      answer_d: 'Everyone must stop working earlier because everything is changing.'
    },
    question_285: {
      question:
        'Mrs. Frost works as a permanent employee in an office. What does she not have to pay out of her salary?',
      answer_a: 'wage tax',
      answer_b: 'unemployment insurance contributions',
      answer_c: 'pension and health insurance contributions',
      answer_d: 'value-added tax (VAT)'
    },
    question_286: {
      question: 'Which organization within a company helps employees with problems with their employer?',
      answer_a: 'the works council',
      answer_b: 'the company auditor',
      answer_c: 'the company group',
      answer_d: 'company management'
    },
    question_287: {
      question: 'You want to end your employment at a company in Germany. What must you take into account?',
      answer_a: 'the salary payments',
      answer_b: 'the working hours',
      answer_c: 'the notice period',
      answer_d: 'the insurance obligation'
    },
    question_288: {
      question: "What is the basis of Germany's special responsibility toward Israel?",
      answer_a: 'membership in the European Union (EU)',
      answer_b: 'the National Socialist crimes against Jews',
      answer_c: 'the Basic Law of the Federal Republic of Germany',
      answer_d: 'Christian tradition'
    },
    question_289: {
      question:
        'A man with dark skin applies for a job as a waiter in a restaurant in Germany. What is an example of discrimination? He does not get the job for the sole reason that ...',
      answer_a: 'his German language skills are too weak.',
      answer_b: 'his salary expectations are too high.',
      answer_c: 'he has dark skin.',
      answer_d: 'he has no experience in the profession.'
    },
    question_290: {
      question:
        'You bought a television in Germany. At home you unpack the television, but it does not work. The television is broken. What can you do?',
      answer_a: 'file a police report',
      answer_b: 'file a complaint about the television',
      answer_c: 'exchange the device without asking',
      answer_d: 'extend the warranty'
    },
    question_291: {
      question:
        'Why do you have to state on your tax return in Germany whether you belong to a church or not? Because ...',
      answer_a: 'there is a church tax that is linked to income and wage tax.',
      answer_b: 'it is important for statistics in Germany.',
      answer_c: 'you have to pay more tax if you do not belong to a church.',
      answer_d: 'the church is responsible for tax returns.'
    },
    question_292: {
      question: 'People in Germany live by the principle of religious tolerance. What does that mean?',
      answer_a: 'No mosques may be built.',
      answer_b: 'All people believe in God.',
      answer_c: 'Everyone can believe whatever they want.',
      answer_d: 'The state decides which God people believe in.'
    },
    question_293: {
      question: 'What is a custom in Germany at Easter?',
      answer_a: 'putting pumpkins in front of the door',
      answer_b: 'decorating a Christmas tree',
      answer_c: 'painting eggs',
      answer_d: 'shooting rockets into the air'
    },
    question_294: {
      question: 'Pentecost is a ...',
      answer_a: 'Christian holiday.',
      answer_b: 'German day of remembrance.',
      answer_c: 'international day of mourning.',
      answer_d: 'Bavarian custom.'
    },
    question_295: {
      question: 'Which religion has shaped European and German culture?',
      answer_a: 'Hinduism',
      answer_b: 'Christianity',
      answer_c: 'Buddhism',
      answer_d: 'Islam'
    },
    question_296: {
      question: 'In Germany, the last four weeks before Christmas are called ...',
      answer_a: 'the Day of Repentance and Prayer.',
      answer_b: 'the harvest festival (Erntedankfest).',
      answer_c: 'Advent.',
      answer_d: "All Saints' Day."
    },
    question_297: {
      question: 'From which country have the most migrants come to Germany?',
      answer_a: 'Italy',
      answer_b: 'Poland',
      answer_c: 'Morocco',
      answer_d: 'Turkey'
    },
    question_298: {
      question: 'In the GDR, the migrants who lived there came mainly from ...',
      answer_a: 'Vietnam, Poland, Mozambique.',
      answer_b: 'France, Romania, Somalia.',
      answer_c: 'Chile, Hungary, Zimbabwe.',
      answer_d: 'North Korea, Mexico, Egypt.'
    },
    question_299: {
      question:
        'Foreign workers who were recruited by the Federal Republic of Germany in the 1950s and 1960s were called ...',
      answer_a: 'undeclared workers.',
      answer_b: 'guest workers.',
      answer_c: 'temporary workers.',
      answer_d: 'shift workers.'
    },
    question_300: {
      question: 'From which country did the first guest workers come to the Federal Republic of Germany?',
      answer_a: 'Italy',
      answer_b: 'Spain',
      answer_c: 'Portugal',
      answer_d: 'Turkey'
    }
  }
}
