// Turns scripts/output/questions-raw.json (from extract-questions.mjs) into
// the final, hand-corrected DE locale file and question-answer-key data,
// cross-referenced with answer-key.ts and the images/ folder.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const RAW_PATH = path.join(__dirname, 'output/questions-raw.json')
const ANSWER_KEY_TS_PATH = path.join(root, 'src/answer-key.ts')
const IMAGES_DIR = path.join(root, 'public/questions')
const DE_LOCALE_OUT = path.join(root, 'src/locales/de.ts')
const DATA_OUT = path.join(root, 'src/data/question-answer-key.ts')

// Hand-verified corrections for PDF text-extraction artifacts (stray
// mid-word spaces, a duplicated caption line, a couple of leading page
// numbers) found during manual review of scripts/output/questions-raw.json.
const QUESTION_FIXES = {
  21: (q) => q.replace(/\s*Bild 1 Bild 2 Bild 3 Bild 4\s*$/, ''),
  184: (q) => q.replace(/^184\.\s*/, ''),
  206: (q) => q.replace(/^206\.\s*/, ''),
  209: (q) => q.replace(/\s*Bild 1 Bild 2 Bild 3 Bild 4\s*$/, ''),
  226: (q) => q.replace(/\s*Bild 1 Bild 2 Bild 3 Bild 4\s*$/, ''),
  8: (q) => q.replace('nicht i m Grundgesetz', 'nicht im Grundgesetz'),
  65: (q) => q.replace('z u den', 'zu den'),
  71: (q) => q.replace('ist s ie/er', 'ist sie/er'),
  100: (q) => q.replace('zu r gesetzlichen', 'zur gesetzlichen'),
  285: (q) => q.replace('Frost a rbeitet', 'Frost arbeitet'),
}

const OPTION_FIXES = {
  // questionNumber: { a|b|c|d: fixer }
  14: { d: (o) => o.replace('mei ne Meinung', 'meine Meinung') },
  71: { c: (o) => o.replace('a uf Schloss', 'auf Schloss') },
  187: { a: (o) => o.replace('P reußen', 'Preußen') },
  300: { a: (o) => o.replace('Ita lien', 'Italien') },
}

function parseAnswerKey() {
  const src = fs.readFileSync(ANSWER_KEY_TS_PATH, 'utf8')
  const m = src.match(/ANSWER_KEY_STRING = `([\s\S]*?)`/)
  if (!m) throw new Error('Could not find ANSWER_KEY_STRING in answer-key.ts')
  const entries = m[1]
    .replaceAll('\n', ' ')
    .split(' ')
    .filter(Boolean)
    .map((str) => {
      const index = [...str].findIndex((c) => Number.isNaN(Number(c)))
      return [Number(str.substring(0, index)), str.substring(index)]
    })
  return new Map(entries)
}

function main() {
  const { questions, anomalies } = JSON.parse(fs.readFileSync(RAW_PATH, 'utf8'))
  if (anomalies.length) {
    throw new Error(`Refusing to generate data: ${anomalies.length} unresolved anomalies`)
  }

  const answerKey = parseAnswerKey()
  const images = new Set(fs.readdirSync(IMAGES_DIR))

  const letters = ['a', 'b', 'c', 'd']
  const deQuestions = {}
  const dataEntries = []

  for (const q of questions.sort((a, b) => a.questionNumber - b.questionNumber)) {
    const questionFix = QUESTION_FIXES[q.questionNumber]
    const question = questionFix ? questionFix(q.question) : q.question

    const optionFixes = OPTION_FIXES[q.questionNumber] || {}
    const options = q.options.map((o, i) => {
      const letter = letters[i]
      const fix = optionFixes[letter]
      return fix ? fix(o) : o
    })

    const answer = answerKey.get(q.questionNumber)
    if (!answer) throw new Error(`No answer-key entry for question ${q.questionNumber}`)

    const imageFile = `${q.questionNumber}.png`
    const questionImage = images.has(imageFile) ? imageFile : undefined

    deQuestions[`question_${q.questionNumber}`] = {
      question,
      answer_a: options[0],
      answer_b: options[1],
      answer_c: options[2],
      answer_d: options[3],
    }

    dataEntries.push({
      questionNumber: q.questionNumber,
      question,
      ...(questionImage ? { questionImage } : {}),
      answer,
      answerOptions: {
        a: { value: 'a', text: options[0] },
        b: { value: 'b', text: options[1] },
        c: { value: 'c', text: options[2] },
        d: { value: 'd', text: options[3] },
      },
    })
  }

  fs.mkdirSync(path.dirname(DE_LOCALE_OUT), { recursive: true })
  fs.writeFileSync(
    DE_LOCALE_OUT,
    `// Auto-generated by scripts/generate-data.mjs. Do not hand-edit generated\n` +
      `// question/answer text here directly for extraction fixes -- edit the\n` +
      `// QUESTION_FIXES/OPTION_FIXES maps in that script and re-run it instead.\n` +
      `export default {\n  questions: ${JSON.stringify(deQuestions, null, 2).replace(/\n/g, '\n  ')},\n}\n`,
  )

  fs.mkdirSync(path.dirname(DATA_OUT), { recursive: true })
  fs.writeFileSync(
    DATA_OUT,
    `import type { QuestionAnswerKey } from '../../types/question-answer-key'\n\n` +
      `// Auto-generated by scripts/generate-data.mjs from the official PDF catalog.\n` +
      `const questionAnswerKey: QuestionAnswerKey = ${JSON.stringify({ questions: dataEntries }, null, 2)}\n\n` +
      `export default questionAnswerKey\n`,
  )

  console.log(`Wrote ${dataEntries.length} questions to de.ts and question-answer-key.ts`)
}

main()
